const todayISO=()=>new Date().toISOString().slice(0,10);const addDays=(n)=>{let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const seed={projects:[{id:'p1',name:'SolidarCAD',color:'#ff6b45'},{id:'p2',name:'БПЛА',color:'#5577e7'},{id:'p3',name:'Обучение',color:'#56a078'}],tasks:[
{id:'t1',title:'Тренировка',date:todayISO(),time:'07:00',duration:90,priority:'P3',project:'',column:'Запланировано',location:'Urban Fitness',tags:['здоровье'],completed:false},
{id:'t2',title:'Урок — Иван',date:todayISO(),time:'09:00',duration:60,priority:'P3',project:'p3',column:'Запланировано',location:'Кабинет 204',tags:['урок'],completed:false},
{id:'t3',title:'Созвон по архитектуре',date:todayISO(),time:'11:00',duration:45,priority:'P2',project:'p1',column:'В работе',location:'Онлайн',tags:['MVP'],completed:false},
{id:'t4',title:'Сделать инструмент Loft',date:todayISO(),time:'14:00',duration:120,priority:'P1',project:'p1',column:'В работе',location:'',tags:['3D','MVP'],completed:false},
{id:'t5',title:'Купить продукты',date:todayISO(),time:'18:30',duration:30,priority:'P4',project:'',column:'Запланировано',location:'',tags:[],completed:false},
{id:'t6',title:'Купить пластик для прототипа',date:todayISO(),time:'',duration:30,priority:'P2',project:'p2',column:'Запланировано',location:'',tags:['закупки'],completed:false},
{id:'t7',title:'Проверить чертёж крыла',date:todayISO(),time:'',duration:60,priority:'P1',project:'p2',column:'В работе',location:'',tags:[],completed:false},
{id:'t8',title:'Оплатить интернет',date:addDays(-1),time:'',duration:15,priority:'P2',project:'',column:'Запланировано',location:'',tags:[],completed:false},
{id:'t9',title:'Изучить API синхронизации',date:addDays(1),time:'12:00',duration:90,priority:'P3',project:'p1',column:'Идеи',location:'',tags:['research'],completed:false},
{id:'t10',title:'Заказать аккумуляторы',date:addDays(2),time:'',duration:30,priority:'P2',project:'p2',column:'Идеи',location:'',tags:['закупки'],completed:false},
{id:'t11',title:'Подготовить тестовый стенд',date:addDays(3),time:'15:00',duration:120,priority:'P3',project:'p2',column:'Запланировано',location:'Мастерская',tags:[],completed:false},
{id:'t12',title:'Настроить CI',date:addDays(-2),time:'',duration:60,priority:'P3',project:'p1',column:'Готово',location:'',tags:['dev'],completed:true}],templates:[{id:'tp1',name:'Урок',icon:'✦',description:'60 минут · P3 · напоминание за 30 минут',duration:60,priority:'P3',location:'Кабинет 204'},{id:'tp2',name:'Тренировка',icon:'⌁',description:'90 минут · спортзал · напоминание за час',duration:90,priority:'P3',location:'Urban Fitness'},{id:'tp3',name:'Встреча',icon:'◌',description:'60 минут · два напоминания',duration:60,priority:'P2',location:''}]};
let state=JSON.parse(localStorage.getItem('plan-state')||'null')||seed;let page='today',calMode='week',projectId=state.projects[0]?.id,query='',apiConnected=false,taskFilter='all',taskSort='date',viewDate=new Date();const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('plan-state',JSON.stringify(state));render();if(apiConnected)fetch('/api/v1/sync',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)}).then(r=>{if(!r.ok)throw Error()}).catch(()=>toast('Нет связи с сервером — сохранено локально'))}function project(id){return state.projects.find(p=>p.id===id)}function formatDate(iso,opt={}){return new Intl.DateTimeFormat('ru-RU',opt).format(new Date(iso+'T12:00:00'))}function color(t){return project(t.project)?.color||'#5577e7'}function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function taskRow(t){let p=project(t.project);return `<div class="task-row ${t.completed?'completed':''}" data-id="${t.id}"><button class="check" aria-label="${t.completed?'Вернуть задачу':'Завершить задачу'}" data-check="${t.id}">${t.completed?'✓':''}</button><div data-edit="${t.id}"><div class="task-name">${t.title}</div><div class="meta"><span class="priority ${t.priority}">${t.priority}</span>${t.date?`<span>▦ ${formatDate(t.date,{day:'numeric',month:'short'})}</span>`:''}${t.time?`<span>◷ ${t.time}</span>`:''}${p?`<span class="pill"><i class="dot" style="display:inline-block;background:${p.color}"></i> ${p.name}</span>`:''}${t.location?`<span>⌖ ${t.location}</span>`:''}</div></div><button class="icon-btn" aria-label="Редактировать ${t.title}" style="width:30px;height:30px" data-edit="${t.id}">···</button></div>`}
function heading(title,sub,extra=''){return `<div class="page-head"><div><span class="eyebrow">ЕЖЕДНЕВНИК</span><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`}
function renderToday(){let day=state.tasks.filter(t=>t.date===todayISO()&&!t.completed),timed=day.filter(t=>t.time).sort((a,b)=>a.time.localeCompare(b.time)),floating=day.filter(t=>!t.time),late=state.tasks.filter(t=>t.date&&t.date<todayISO()&&!t.completed);let done=state.tasks.filter(t=>t.date===todayISO()&&t.completed).length,total=day.length+done;return heading('Сегодня',formatDate(todayISO(),{weekday:'long',day:'numeric',month:'long'}),`<div class="date-nav"><button>‹</button><button>Сегодня</button><button>›</button></div>`)+`<div class="stats"><div class="stat"><strong>${day.length}</strong><small>задач сегодня</small></div><div class="stat"><strong>${timed.reduce((s,t)=>s+t.duration,0)/60}ч</strong><small>запланировано</small></div><div class="stat"><strong>${total?Math.round(done/total*100):0}%</strong><small>выполнено</small></div></div><div class="dashboard"><div><section class="card"><div class="card-title"><span>Расписание</span><b>${timed.length}</b></div>${timed.map(t=>`<div class="timeline-item" style="--task-color:${color(t)}"><div class="time">${t.time}<small>${String(Math.floor((+t.time.slice(0,2)*60 + +t.time.slice(3)+t.duration)/60)).padStart(2,'0')}:${String((+t.time.slice(3)+t.duration)%60).padStart(2,'0')}</small></div><div class="rail"></div><div class="event"><strong>${t.title}</strong><small>${project(t.project)?.name||'Личное'}${t.location?' · '+t.location:''}</small></div></div>`).join('')||'<div class="empty">На сегодня нет событий</div>'}</section></div><div><section class="card"><div class="card-title"><span>Без времени</span><b>${floating.length}</b></div>${floating.map(taskRow).join('')||'<div class="empty">Всё запланировано</div>'}<form class="quick" id="quick"><input name="title" required placeholder="Добавить задачу…"><button class="primary">＋</button></form></section>${late.length?`<section class="card overdue" style="margin-top:18px"><div class="card-title"><span>Просрочено</span><b>${late.length}</b></div>${late.map(taskRow).join('')}</section>`:''}</div></div>`}
function renderTasks(inbox=false){let list=state.tasks.filter(t=>inbox?!t.date:true).filter(t=>!query||JSON.stringify(t).toLowerCase().includes(query));return heading(inbox?'Входящие':'Все задачи',inbox?'Задачи, которые ещё не запланированы':'Единый список дел из календаря и проектов',`<button class="primary" data-add>＋ Новая задача</button>`)+`<div class="toolbar"><div class="segmented"><button class="active">Все</button><button>Активные</button><button>Готово</button></div><select class="filter"><option>По дате</option><option>По приоритету</option></select></div><section class="card">${list.map(taskRow).join('')||'<div class="empty">Задач не найдено</div>'}</section>`}
function renderCalendar(){let modes=['day','week','month','agenda'],names=['День','Неделя','Месяц','Повестка'];let controls=`<div class="segmented">${modes.map((m,i)=>`<button data-cal="${m}" class="${calMode===m?'active':''}">${names[i]}</button>`).join('')}</div>`;let body='';if(calMode==='month'){let base=new Date(),y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-(first.getDay()||7)+1);body='<div class="month-grid">'+Array.from({length:42},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let iso=d.toISOString().slice(0,10),items=state.tasks.filter(t=>t.date===iso);return `<div class="month-day ${d.getMonth()!==m?'muted':''} ${iso===todayISO()?'today':''}"><b>${d.getDate()}</b>${items.slice(0,3).map(t=>`<div class="month-event" style="border-left:2px solid ${color(t)}">${t.time||'Весь день'} ${t.title}</div>`).join('')}</div>`}).join('')+'</div>'}else if(calMode==='agenda'){let list=state.tasks.filter(t=>t.date>=todayISO()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));body=`<section class="card">${list.map(t=>`<div class="task-row"><div><b>${formatDate(t.date,{day:'numeric',month:'short'})}</b><small style="display:block;color:var(--muted)">${t.time||'Весь день'}</small></div><div>${taskRow(t)}</div></div>`).join('')}</section>`}else{let days=calMode==='day'?[new Date()]:Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);return d});let hours=Array.from({length:12},(_,i)=>i+7);body=`<div class="calendar-wrap"><div class="calendar-grid" style="grid-template-columns:54px repeat(${days.length},1fr)"><div class="cal-head"></div>${days.map(d=>`<div class="cal-head ${d.toISOString().slice(0,10)===todayISO()?'today':''}">${formatDate(d.toISOString().slice(0,10),{weekday:'short',day:'numeric'})}</div>`).join('')}${hours.map(h=>`<div class="cal-time">${String(h).padStart(2,'0')}:00</div>${days.map(d=>{let iso=d.toISOString().slice(0,10),it=state.tasks.filter(t=>t.date===iso&&+t.time.slice(0,2)===h);return `<div class="cal-cell">${it.map(t=>`<div class="cal-event" style="border-color:${color(t)}">${t.time} ${t.title}</div>`).join('')}</div>`}).join('')}`).join('')}</div></div>`}return heading('Календарь','Все события и задачи с датой',controls)+body}
function renderProjects(){let p=project(projectId)||state.projects[0];let cols=['Идеи','Запланировано','В работе','Готово'];return heading('Проекты','Задачи, объединённые общей целью',`<select class="filter" id="project-picker">${state.projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.name}</option>`).join('')}</select>`)+`<div class="kanban">${cols.map(c=>{let ts=state.tasks.filter(t=>t.project===p.id&&t.column===c);return `<div class="kanban-col" data-column="${c}"><div class="col-head"><span>${c}</span><span>${ts.length}</span></div>${ts.map(t=>`<article class="kanban-card" draggable="true" data-drag="${t.id}"><div class="tags"><span class="priority ${t.priority}">${t.priority}</span>${t.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><h4>${t.title}</h4><div class="meta">${t.date?`<span>▦ ${formatDate(t.date,{day:'numeric',month:'short'})}</span>`:''}${t.time?`<span>◷ ${t.time}</span>`:''}</div></article>`).join('')}</div>`}).join('')}</div>`}
function renderTemplates(){return heading('Шаблоны','Создавайте частые события за несколько секунд',`<button class="primary">＋ Новый шаблон</button>`)+`<div class="template-grid">${state.templates.map(t=>`<article class="template-card"><div class="template-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.description}</p><button class="secondary" data-template="${t.id}">Использовать</button></article>`).join('')}<article class="template-card" style="border-style:dashed;display:grid;place-items:center;text-align:center"><div><div class="template-icon" style="margin:auto">＋</div><h3>Создать шаблон</h3><p>Настройте поля под свой сценарий</p></div></article></div>`}
function renderSettings(){return heading('Настройки','Аккаунт, уведомления и интеграции')+`<div class="project-grid"><section class="card"><div class="card-title">Профиль</div><p><b>Дмитрий</b><br><small style="color:var(--muted)">Europe/Moscow · русский</small></p><button class="secondary">Изменить профиль</button></section><section class="card"><div class="card-title">Google Calendar <b>не подключён</b></div><p style="font-size:12px;color:var(--muted)">Подключите аккаунт для двусторонней синхронизации и отображения событий в Samsung Calendar.</p><button class="primary" id="google-btn">Подключить</button></section><section class="card"><div class="card-title">Данные</div><p style="font-size:12px;color:var(--muted)">Сейчас данные безопасно хранятся в этом браузере.</p><button class="secondary" id="reset-btn">Восстановить демо</button></section></div>`}
function render(){let content=page==='today'?renderToday():page==='calendar'?renderCalendar():page==='tasks'?renderTasks():page==='projects'?renderProjects():page==='inbox'?renderTasks(true):page==='templates'?renderTemplates():renderSettings();$('#content').innerHTML=content;$('#today-count').textContent=state.tasks.filter(t=>t.date===todayISO()&&!t.completed).length;$('#inbox-count').textContent=state.tasks.filter(t=>!t.date&&!t.completed).length;$('#side-projects').innerHTML=state.projects.map(p=>`<div class="project-link"><i class="dot" style="background:${p.color}"></i>${p.name}</div>`).join('');$('#project-select').innerHTML='<option value="">Без проекта</option>'+state.projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');bindDynamic()}
function openModal(task=null){let f=$('#task-form');f.reset();f.elements.date.value=t?.date||todayISO();f.elements.duration.value=t?.duration||60;if(t)Object.keys(t).forEach(k=>{if(f.elements[k])f.elements[k].value=Array.isArray(t[k])?t[k].join(', '):t[k]});$('#modal').classList.remove('hidden');setTimeout(()=>f.elements.title.focus(),50)}function closeModal(){$('#modal').classList.add('hidden')}
function bindDynamic(){$$('[data-add]').forEach(b=>b.onclick=()=>openModal());$$('[data-check]').forEach(b=>b.onclick=()=>{let t=state.tasks.find(x=>x.id===b.dataset.check);t.completed=!t.completed;if(t.completed)t.column='Готово';save();toast(t.completed?'Задача выполнена':'Задача возвращена')});$$('[data-edit]').forEach(b=>b.onclick=()=>openModal(state.tasks.find(x=>x.id===b.dataset.edit)));$$('[data-cal]').forEach(b=>b.onclick=()=>{calMode=b.dataset.cal;render()});$$('[data-template]').forEach(b=>b.onclick=()=>{let t=state.templates.find(x=>x.id===b.dataset.template);openModal({title:t.name,date:todayISO(),duration:t.duration,priority:t.priority,location:t.location,column:'Запланировано',tags:[]})});let q=$('#quick');if(q)q.onsubmit=e=>{e.preventDefault();state.tasks.push({id:crypto.randomUUID(),title:q.title.value,date:todayISO(),time:'',duration:30,priority:'P3',project:'',column:'Запланировано',location:'',tags:[],completed:false});save();toast('Задача добавлена')};let picker=$('#project-picker');if(picker)picker.onchange=()=>{projectId=picker.value;render()};$$('[data-drag]').forEach(c=>{c.ondragstart=()=>{c.classList.add('dragging');window.dragId=c.dataset.drag};c.ondragend=()=>c.classList.remove('dragging')});$$('[data-column]').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=()=>{state.tasks.find(t=>t.id===window.dragId).column=c.dataset.column;save();toast('Задача перемещена')}});let g=$('#google-btn');if(g)g.onclick=()=>toast('Для подключения нужен OAuth backend');let reset=$('#reset-btn');if(reset)reset.onclick=()=>{localStorage.removeItem('plan-state');state=structuredClone(seed);save();toast('Демо-данные восстановлены')}}
$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('open');render()};$('#task-form').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),old=state.tasks.find(t=>t.id===d.id);let task={...old,...d,id:d.id||crypto.randomUUID(),duration:+d.duration,tags:d.tags.split(',').map(x=>x.trim()).filter(Boolean),completed:old?.completed||false};if(old)Object.assign(old,task);else state.tasks.push(task);closeModal();save();toast(old?'Задача обновлена':'Задача создана')};$$('[data-close]').forEach(b=>b.onclick=closeModal);$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#menu-btn').onclick=()=>$('#sidebar').classList.toggle('open');$('#theme-btn').onclick=()=>document.body.classList.toggle('dark');$('#search').oninput=e=>{query=e.target.value.toLowerCase();if(query){page='tasks';render()}else render()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')closeModal()});
async function init(){render();try{let auth=await fetch('/api/v1/auth/demo',{method:'POST',credentials:'include'});if(!auth.ok)throw Error();let r=await fetch('/api/v1/bootstrap',{credentials:'include'});if(!r.ok)throw Error();let remote=await r.json();apiConnected=true;if(remote.tasks.length){state={projects:remote.projects,tasks:remote.tasks,templates:remote.templates};localStorage.setItem('plan-state',JSON.stringify(state))}else{await fetch('/api/v1/sync',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)})}projectId=state.projects[0]?.id;render();toast('Сервер и база данных подключены')}catch(e){apiConnected=false;render()}}init();

// Интерактивный слой 1.0: все представления используют одни обработчики задач.
function renderTasks(inbox=false){
  let list=state.tasks.filter(t=>inbox?!t.date:true).filter(t=>!query||JSON.stringify(t).toLowerCase().includes(query));
  if(taskFilter==='active')list=list.filter(t=>!t.completed);if(taskFilter==='done')list=list.filter(t=>t.completed);
  const rank={P1:1,P2:2,P3:3,P4:4};list=[...list].sort(taskSort==='priority'?(a,b)=>rank[a.priority]-rank[b.priority]:(a,b)=>(a.date||'9999')+(a.time||'99:99')>((b.date||'9999')+(b.time||'99:99'))?1:-1);
  return heading(inbox?'Входящие':'Все задачи',inbox?'Задачи, которые ещё не запланированы':'Единый список дел из календаря и проектов',`<button class="primary" data-add>＋ Новая задача</button>`)+`<div class="toolbar"><div class="segmented"><button data-task-filter="all" class="${taskFilter==='all'?'active':''}">Все</button><button data-task-filter="active" class="${taskFilter==='active'?'active':''}">Активные</button><button data-task-filter="done" class="${taskFilter==='done'?'active':''}">Готово</button></div><select class="filter" id="task-sort"><option value="date" ${taskSort==='date'?'selected':''}>По дате</option><option value="priority" ${taskSort==='priority'?'selected':''}>По приоритету</option></select></div><section class="card">${list.map(taskRow).join('')||'<div class="empty">Задач не найдено</div>'}</section>`
}
function renderToday(){
  const iso=viewDate.toISOString().slice(0,10),day=state.tasks.filter(t=>t.date===iso&&!t.completed),timed=day.filter(t=>t.time).sort((a,b)=>a.time.localeCompare(b.time)),floating=day.filter(t=>!t.time),late=iso===todayISO()?state.tasks.filter(t=>t.date&&t.date<todayISO()&&!t.completed):[],done=state.tasks.filter(t=>t.date===iso&&t.completed).length,total=day.length+done;
  return heading(iso===todayISO()?'Сегодня':formatDate(iso,{day:'numeric',month:'long'}),formatDate(iso,{weekday:'long',day:'numeric',month:'long'}),`<div class="date-nav"><button data-date-nav="-1">‹</button><button data-date-nav="today">Сегодня</button><button data-date-nav="1">›</button></div>`)+`<div class="stats"><div class="stat"><strong>${day.length}</strong><small>задач</small></div><div class="stat"><strong>${(timed.reduce((s,t)=>s+t.duration,0)/60).toFixed(1).replace('.0','')}ч</strong><small>запланировано</small></div><div class="stat"><strong>${total?Math.round(done/total*100):0}%</strong><small>выполнено</small></div></div><div class="dashboard"><section class="card"><div class="card-title"><span>Расписание</span><b>${timed.length}</b></div>${timed.map(t=>`<div class="timeline-item" style="--task-color:${color(t)}"><div class="time">${t.time}</div><div class="rail"></div><div class="event" data-edit="${t.id}"><strong>${t.title}</strong><small>${project(t.project)?.name||'Личное'}${t.location?' · '+t.location:''}</small></div></div>`).join('')||'<div class="empty">На этот день нет событий</div>'}</section><div><section class="card"><div class="card-title"><span>Без времени</span><b>${floating.length}</b></div>${floating.map(taskRow).join('')||'<div class="empty">Всё запланировано</div>'}<form class="quick" id="quick"><input name="title" required placeholder="Добавить задачу…"><button class="primary">＋</button></form></section>${late.length?`<section class="card overdue" style="margin-top:18px"><div class="card-title"><span>Просрочено</span><b>${late.length}</b></div>${late.map(taskRow).join('')}</section>`:''}</div></div>`
}
function renderCalendar(){
  const modes=[['day','День'],['week','Неделя'],['month','Месяц'],['agenda','Повестка']],controls=`<div style="display:flex;gap:10px"><div class="date-nav"><button data-cal-nav="-1">‹</button><button data-cal-nav="today">Сегодня</button><button data-cal-nav="1">›</button></div><div class="segmented">${modes.map(([m,n])=>`<button data-cal="${m}" class="${calMode===m?'active':''}">${n}</button>`).join('')}</div></div>`;let body='';
  if(calMode==='month'){let y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-(first.getDay()||7)+1);body='<div class="month-grid">'+Array.from({length:42},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let iso=d.toISOString().slice(0,10),items=state.tasks.filter(t=>t.date===iso);return `<div class="month-day ${d.getMonth()!==m?'muted':''} ${iso===todayISO()?'today':''}" data-new-date="${iso}"><b>${d.getDate()}</b>${items.slice(0,4).map(t=>`<div class="month-event" data-edit="${t.id}" style="border-left:2px solid ${color(t)}">${t.time||'Весь день'} ${t.title}</div>`).join('')}</div>`}).join('')+'</div>'}
  else if(calMode==='agenda'){let from=viewDate.toISOString().slice(0,10),list=state.tasks.filter(t=>t.date>=from).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));body=`<section class="card">${list.map(taskRow).join('')||'<div class="empty">Нет ближайших задач</div>'}</section>`}
  else{let days=calMode==='day'?[new Date(viewDate)]:Array.from({length:7},(_,i)=>{let d=new Date(viewDate);d.setDate(d.getDate()-((d.getDay()+6)%7)+i);return d}),hours=Array.from({length:14},(_,i)=>i+7);body=`<div class="calendar-wrap"><div class="calendar-grid" style="grid-template-columns:54px repeat(${days.length},1fr)"><div class="cal-head"></div>${days.map(d=>`<div class="cal-head ${d.toISOString().slice(0,10)===todayISO()?'today':''}">${formatDate(d.toISOString().slice(0,10),{weekday:'short',day:'numeric'})}</div>`).join('')}${hours.map(h=>`<div class="cal-time">${String(h).padStart(2,'0')}:00</div>${days.map(d=>{let iso=d.toISOString().slice(0,10),it=state.tasks.filter(t=>t.date===iso&&t.time&&+t.time.slice(0,2)===h);return `<div class="cal-cell" data-new-date="${iso}" data-new-time="${String(h).padStart(2,'0')}:00">${it.map(t=>`<div class="cal-event" data-edit="${t.id}" style="border-color:${color(t)}">${t.time} ${t.title}</div>`).join('')}</div>`}).join('')}`).join('')}</div></div>`}
  return heading('Календарь',formatDate(viewDate.toISOString().slice(0,10),{month:'long',year:'numeric'}),controls)+body
}
function renderProjects(){let p=project(projectId)||state.projects[0],cols=['Идеи','Запланировано','В работе','Готово'];if(!p)return heading('Проекты','Создайте первый проект',`<button class="primary" data-new-project>＋ Новый проект</button>`);return heading('Проекты','Задачи, объединённые общей целью',`<div style="display:flex;gap:8px"><select class="filter" id="project-picker">${state.projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.name}</option>`).join('')}</select><button class="primary" data-new-project>＋ Проект</button></div>`)+`<div class="kanban">${cols.map(c=>{let ts=state.tasks.filter(t=>t.project===p.id&&t.column===c);return `<div class="kanban-col" data-column="${c}"><div class="col-head"><span>${c}</span><span>${ts.length}</span></div>${ts.map(t=>`<article class="kanban-card" draggable="true" data-drag="${t.id}" data-edit="${t.id}"><div class="tags"><span class="priority ${t.priority}">${t.priority}</span>${t.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><h4>${t.title}</h4><div class="meta">${t.date?`<span>▦ ${formatDate(t.date,{day:'numeric',month:'short'})}</span>`:''}${t.time?`<span>◷ ${t.time}</span>`:''}</div></article>`).join('')}<button class="secondary" style="width:100%" data-add-column="${c}">＋ Задача</button></div>`}).join('')}</div>`}
function renderTemplates(){return heading('Шаблоны','Создавайте частые события за несколько секунд',`<button class="primary" data-new-template>＋ Новый шаблон</button>`)+`<div class="template-grid">${state.templates.map(t=>`<article class="template-card"><div class="template-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.description}</p><button class="secondary" data-template="${t.id}">Использовать</button></article>`).join('')}<button class="template-card" data-new-template style="border-style:dashed;text-align:center"><div class="template-icon" style="margin:auto">＋</div><h3>Создать шаблон</h3><p>Настройте поля под свой сценарий</p></button></div>`}
function openModal(task=null){let f=$('#task-form');f.reset();f.elements.date.value=task?.date||viewDate.toISOString().slice(0,10);f.elements.duration.value=task?.duration||60;if(task)Object.keys(task).forEach(k=>{if(f.elements[k])f.elements[k].value=Array.isArray(task[k])?task[k].join(', '):task[k]});$('#delete-task').classList.toggle('hidden',!task?.id);$('#modal').classList.remove('hidden');setTimeout(()=>f.elements.title.focus(),50)}
function bindDynamic(){
  $$('[data-add]').forEach(b=>b.onclick=()=>openModal());$$('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openModal(state.tasks.find(x=>x.id===b.dataset.edit))});
  $$('[data-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();let t=state.tasks.find(x=>x.id===b.dataset.check);t.completed=!t.completed;t.column=t.completed?'Готово':(t.column==='Готово'?'Запланировано':t.column);save();toast(t.completed?'Задача выполнена':'Задача возвращена')});
  $$('[data-task-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.taskFilter;render()});let sort=$('#task-sort');if(sort)sort.onchange=()=>{taskSort=sort.value;render()};
  $$('[data-date-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.dateNav==='today')viewDate=new Date();else viewDate.setDate(viewDate.getDate()+ +b.dataset.dateNav);render()});$$('[data-cal-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.calNav==='today')viewDate=new Date();else{let step=calMode==='month'?30:calMode==='week'?7:1;viewDate.setDate(viewDate.getDate()+step*+b.dataset.calNav)}render()});$$('[data-cal]').forEach(b=>b.onclick=()=>{calMode=b.dataset.cal;render()});
  $$('[data-new-date]').forEach(c=>c.ondblclick=e=>{if(e.target.closest('[data-edit]'))return;openModal({date:c.dataset.newDate,time:c.dataset.newTime||'',duration:60,priority:'P3',column:'Запланировано',tags:[]})});
  $$('[data-template]').forEach(b=>b.onclick=()=>{let t=state.templates.find(x=>x.id===b.dataset.template);openModal({title:t.name,date:todayISO(),duration:t.duration,priority:t.priority,location:t.location,column:'Запланировано',tags:[]})});
  $$('[data-new-template]').forEach(b=>b.onclick=()=>{let name=prompt('Название нового шаблона');if(!name)return;state.templates.push({id:crypto.randomUUID(),name,icon:'✦',description:'60 минут · P3',duration:60,priority:'P3',location:''});save();toast('Шаблон создан')});
  $$('[data-new-project]').forEach(b=>b.onclick=()=>{let name=prompt('Название нового проекта');if(!name)return;let p={id:crypto.randomUUID(),name,color:'#5577e7'};state.projects.push(p);projectId=p.id;save();toast('Проект создан')});
  $$('[data-add-column]').forEach(b=>b.onclick=()=>openModal({project:projectId,column:b.dataset.addColumn,date:'',duration:60,priority:'P3',tags:[]}));
  let q=$('#quick');if(q)q.onsubmit=e=>{e.preventDefault();state.tasks.push({id:crypto.randomUUID(),title:q.title.value,date:viewDate.toISOString().slice(0,10),time:'',duration:30,priority:'P3',project:'',column:'Запланировано',location:'',tags:[],completed:false});save();toast('Задача добавлена')};let picker=$('#project-picker');if(picker)picker.onchange=()=>{projectId=picker.value;render()};
  $$('[data-drag]').forEach(c=>{c.ondragstart=e=>{c.classList.add('dragging');window.dragId=c.dataset.drag;e.stopPropagation()};c.ondragend=()=>c.classList.remove('dragging')});$$('[data-column]').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();let t=state.tasks.find(x=>x.id===window.dragId);if(t){t.column=c.dataset.column;t.completed=c.dataset.column==='Готово';save();toast('Задача перемещена')}}});
  $$('[data-side-project]').forEach(b=>b.onclick=()=>{projectId=b.dataset.sideProject;page='projects';render()});let g=$('#google-btn');if(g)g.onclick=()=>toast('Google OAuth будет подключён после добавления ключей');let reset=$('#reset-btn');if(reset)reset.onclick=()=>{state=structuredClone(seed);projectId=state.projects[0].id;save();toast('Демо-данные восстановлены')};let profile=$('#profile-btn');if(profile)profile.onclick=()=>toast('Профиль демо-пользователя активен')
}
function render(){let content=page==='today'?renderToday():page==='calendar'?renderCalendar():page==='tasks'?renderTasks():page==='projects'?renderProjects():page==='inbox'?renderTasks(true):page==='templates'?renderTemplates():renderSettings();$('#content').innerHTML=content;$('#today-count').textContent=state.tasks.filter(t=>t.date===todayISO()&&!t.completed).length;$('#inbox-count').textContent=state.tasks.filter(t=>!t.date&&!t.completed).length;$('#side-projects').innerHTML=state.projects.map(p=>`<button class="project-link" data-side-project="${p.id}"><i class="dot" style="background:${p.color}"></i>${p.name}</button>`).join('');$('#project-select').innerHTML='<option value="">Без проекта</option>'+state.projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');bindDynamic()}
$('#delete-task').onclick=()=>{let id=$('#task-form').elements.id.value;if(!id)return;state.tasks=state.tasks.filter(t=>t.id!==id);closeModal();save();toast('Задача удалена')};$('.avatar').onclick=()=>{page='settings';render()};
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===nav));$('#sidebar').classList.remove('open');render();return}if(e.target.closest('#theme-btn'))document.body.classList.toggle('dark');if(e.target.closest('#menu-btn'))$('#sidebar').classList.toggle('open');if(e.target.closest('.avatar')){page='settings';render()}});
function handleClick(e){
  let b=e.target.closest('[data-page]');if(b){page=b.dataset.page;$('#sidebar').classList.remove('open');render();return}
  b=e.target.closest('[data-add]');if(b){openModal();return}b=e.target.closest('[data-edit]');if(b){e.stopPropagation();openModal(state.tasks.find(t=>t.id===b.dataset.edit));return}
  b=e.target.closest('[data-check]');if(b){e.stopPropagation();let t=state.tasks.find(x=>x.id===b.dataset.check);t.completed=!t.completed;t.column=t.completed?'Готово':'Запланировано';save();toast(t.completed?'Задача выполнена':'Задача возвращена');return}
  b=e.target.closest('[data-task-filter]');if(b){taskFilter=b.dataset.taskFilter;render();return}b=e.target.closest('[data-cal]');if(b){calMode=b.dataset.cal;render();return}
  b=e.target.closest('[data-date-nav]');if(b){if(b.dataset.dateNav==='today')viewDate=new Date();else viewDate.setDate(viewDate.getDate()+ +b.dataset.dateNav);render();return}
  b=e.target.closest('[data-cal-nav]');if(b){if(b.dataset.calNav==='today')viewDate=new Date();else viewDate.setDate(viewDate.getDate()+(calMode==='month'?30:calMode==='week'?7:1)*+b.dataset.calNav);render();return}
  b=e.target.closest('[data-template]');if(b){let t=state.templates.find(x=>x.id===b.dataset.template);openModal({title:t.name,date:todayISO(),duration:t.duration,priority:t.priority,location:t.location,column:'Запланировано',tags:[]});return}
  b=e.target.closest('[data-add-column]');if(b){openModal({project:projectId,column:b.dataset.addColumn,date:'',duration:60,priority:'P3',tags:[]});return}
  b=e.target.closest('[data-side-project]');if(b){projectId=b.dataset.sideProject;page='projects';$('#sidebar').classList.remove('open');render();return}
  b=e.target.closest('[data-new-project]');if(b){let name=prompt('Название нового проекта');if(name){let p={id:crypto.randomUUID(),name,color:'#5577e7'};state.projects.push(p);projectId=p.id;save();toast('Проект создан')}return}
  b=e.target.closest('[data-new-template]');if(b){let name=prompt('Название нового шаблона');if(name){state.templates.push({id:crypto.randomUUID(),name,icon:'✦',description:'60 минут · P3',duration:60,priority:'P3',location:''});save();toast('Шаблон создан')}return}
  if(e.target.closest('#menu-btn')){$('#sidebar').classList.toggle('open');return}if(e.target.closest('#theme-btn')){document.body.classList.toggle('dark');return}if(e.target.closest('.avatar')){page='settings';render();return}
  if(e.target.closest('#google-btn')){toast('Google OAuth будет подключён после добавления ключей');return}if(e.target.closest('#reset-btn')){state=structuredClone(seed);projectId=state.projects[0].id;save();toast('Демо-данные восстановлены');return}
  if(e.target.closest('button')?.textContent.includes('Изменить профиль')){toast('Редактирование профиля будет доступно после выхода из демо-режима');return}
  if(e.target.closest('#delete-task')){let id=$('#task-form').elements.id.value;if(id){state.tasks=state.tasks.filter(t=>t.id!==id);closeModal();save();toast('Задача удалена')}return}
  if(e.target.closest('[data-close]')){closeModal();return}
}
function handleChange(e){if(e.target.id==='task-sort'){taskSort=e.target.value;render()}if(e.target.id==='project-picker'){projectId=e.target.value;render()}}
function handleDoubleClick(e){let c=e.target.closest('[data-new-date]');if(c&&!e.target.closest('[data-edit]'))openModal({date:c.dataset.newDate,time:c.dataset.newTime||'',duration:60,priority:'P3',column:'Запланировано',tags:[]})}
function handleSubmit(e){e.preventDefault();if(e.target.id==='quick'){let title=e.target.elements.title.value.trim();if(title){state.tasks.push({id:crypto.randomUUID(),title,date:viewDate.toISOString().slice(0,10),time:'',duration:30,priority:'P3',project:'',column:'Запланировано',location:'',tags:[],completed:false});save();toast('Задача добавлена')}return}if(e.target.id==='task-form'){let d=Object.fromEntries(new FormData(e.target)),old=state.tasks.find(t=>t.id===d.id),task={...old,...d,id:d.id||crypto.randomUUID(),duration:+d.duration,tags:d.tags.split(',').map(x=>x.trim()).filter(Boolean),completed:old?.completed||false};if(old)Object.assign(old,task);else state.tasks.push(task);closeModal();save();toast(old?'Задача обновлена':'Задача создана')}}
