import {renderGoals,handleGoalAction,goalOptions} from './frontend/js/goals.js';
import {renderFinance,bindFinance} from './frontend/js/finance.js';
let goalPeriod='week',goalDate=new Date().toLocaleDateString('en-CA');
document.addEventListener('click',async e=>{const button=e.target.closest('[data-goal-action]');if(!button)return;try{await handleGoalAction(button,{state:S,dialog:uiDialog,api,openTask,refresh:refreshRealtime,period:goalPeriod,date:goalDate})}catch(error){toast(error.message)}});
document.addEventListener('change',e=>{if(e.target.id==='goal-period'){goalPeriod=e.target.value;render()}if(e.target.id==='goal-date'&&e.target.value){goalDate=e.target.value;render()}if(e.target.name==='goal')updateGoalHint()});
function updateGoalHint(){const goal=S.goals.find(g=>g.id===$('#task-goal').value);$('#task-goal-why').textContent=goal?.why||''}
import {renderAI} from './frontend/js/ai.js';
document.addEventListener('ai-tasks-changed',()=>refreshRealtime());
document.addEventListener('ai-open-task',async e=>{try{openTask(await api('/tasks/'+e.detail))}catch(error){toast(error.message)}});
import {api} from './frontend/js/api.js';
import {profileCard,editProfile,updateProfileAvatar} from './frontend/js/profile.js';
import {calendarMovePatch} from './frontend/js/calendar.js';

document.addEventListener('click',async e=>{if(!e.target.closest('[data-profile-edit]'))return;try{const user=await editProfile(S.user,uiDialog,api);if(user){S.user=user;render();toast('Профиль сохранён')}}catch(error){toast(error.message)}});

document.addEventListener('click',async e=>{if(!e.target.closest('#friends-alert'))return;let items=S.notifications||[],body=(items.map(n=>`<div class="notification-item notification-${n.priority||'normal'}"><span class="notification-channel">${n.channel==='alarm'?'⏰':n.channel==='sound'?'♪':'🔔'}</span><b>${esc(n.title)}</b>${n.type==='friend_incoming'?`<div><button class="primary" data-friend-request="accept" data-id="${n.request_id}">Принять</button> <button class="secondary" data-friend-request="reject" data-id="${n.request_id}">Отклонить</button></div>`:''}</div>`).join('')||'<div class="empty">Новых уведомлений нет</div>')+(items.length?'<div class="notification-actions"><button type="button" class="secondary" data-action="clearnotifications">Очистить уведомления</button></div>':'');await uiDialog('Уведомления',body,'Закрыть')});
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action="clearnotifications"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();try{await api('/notifications/clear',{method:'POST'});S.notifications=[];closeUi();render();toast('Уведомления очищены')}catch(x){toast(x.message)}},true);
document.addEventListener('click',e=>{let b=e.target.closest('[data-action="adddate"],[data-action="openday"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();let date=b.dataset.date;if(b.dataset.action==='openday'){viewDate=new Date(`${date}T12:00:00`);calMode='day';render()}else openTask({}, {date})},true);
document.addEventListener('change',e=>{let f=e.target.closest('#task-form');if(!f)return;if(e.target.name==='time'||e.target.name==='duration'){let date=f.date.value,time=f.time.value;if(!date||!time)return;let end=new Date(`${date}T${time}:00`);end.setMinutes(end.getMinutes()+(+f.duration.value||60));f.end_time.value=`${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`}if(e.target.name==='end_time'&&f.time.value&&f.end_time.value){let start=new Date(`2000-01-01T${f.time.value}:00`),end=new Date(`2000-01-01T${f.end_time.value}:00`),minutes=Math.round((end-start)/60000);if(minutes>0&&[...f.duration.options].some(o=>+o.value===minutes))f.duration.value=String(minutes)}},true);
document.addEventListener('change',async e=>{if(e.target.id!=='task-template-choice')return;let f=$('#task-form'),choice=e.target.value;if(choice==='__create__'){let result=await uiDialog('Новый шаблон','<label>Название шаблона<input name="name" required placeholder="Например, Еженедельный отчёт"></label>','Продолжить');if(!result){fillTemplateOptions(f,'');updateTemplateActions(f);return}f.dataset.templateName=result.name.trim();updateTemplateActions(f);return}delete f.dataset.templateName;if(!choice){updateTemplateActions(f);return}let template=S.templates.find(x=>x.id===choice);if(template)openTask(template.task_data||{}, {templateChoice:choice})},true);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action="archive"],[data-action="restore"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();try{let restoring=b.dataset.action==='restore',source=restoring?S.archived:S.tasks,t=source.find(x=>x.id===b.dataset.id),updated=await api(`/tasks/${t.id}/${restoring?'restore':'archive'}`,{method:'POST'});if(restoring){S.archived=S.archived.filter(x=>x.id!==t.id);S.tasks.push(updated)}else{S.tasks=S.tasks.filter(x=>x.id!==t.id);S.archived.push(updated)}render();toast(restoring?'Задача восстановлена':'Задача перемещена в архив')}catch(x){toast(x.message)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action="assignself"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();try{let updated=await api(`/tasks/${b.dataset.id}/assign-self`,{method:'POST'});S.tasks=S.tasks.map(t=>t.id===updated.id?updated:t);render();toast('Задача назначена вам')}catch(x){toast(x.message)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action="deleteproject"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();let p=project(projectId),data=await uiDialog(`Удалить проект «${esc(p.name)}»?`,`<p>Проект исчезнет у всех участников. Переписка и состав команды сохранятся в базе.</p><label>Что сделать с задачами<select name="task_policy"><option value="keep">Оставить как личные задачи их авторов</option><option value="archive">Переместить все задачи в архив</option><option value="delete">Удалить задачи вместе с проектом</option></select></label>`,'Удалить проект');if(!data)return;try{await api(`/projects/${p.id}/delete`,{method:'POST',body:JSON.stringify(data)});if(data.task_policy==='keep')S.tasks.forEach(t=>{if(t.project_id===p.id){t.project_id=null;t.column_id=null;if(t.assigned_to_id!==t.user_id)t.assigned_to_id=null}});if(data.task_policy==='archive'){let moved=S.tasks.filter(t=>t.project_id===p.id).map(t=>({...t,archived_at:new Date().toISOString()}));S.tasks=S.tasks.filter(t=>t.project_id!==p.id);S.archived.push(...moved)}if(data.task_policy==='delete')S.tasks=S.tasks.filter(t=>t.project_id!==p.id);S.projects=S.projects.filter(x=>x.id!==p.id);projectId=S.projects[0]?.id||null;render();toast('Проект удалён')}catch(x){toast(x.message)}},true);

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10);
let S={goals:[],user:null,projects:[],tasks:[],archived:[],templates:[],contacts:[],friendRequests:[],friendRoles:[],notifications:[]},page='today',viewDate=new Date(),calMode='week',projectId=null,taskFilter='active',taskSort='date',query='',authRegister=false,dragTask=null,calendarDropUntil=0,friendResults=[];
bindFinance({state:S,api,dialog:uiDialog,reload:load,toast});
let realtimeSource=null,realtimeRefresh=null;
const themes=['sunrise','mist','midnight'];
function applyTheme(theme,notify=false){
  let next=themes.includes(theme)?theme:'sunrise';
  document.body.dataset.theme=next;
  document.body.classList.toggle('dark',next==='midnight');
  localStorage.setItem('planner-theme',next);
  let button=$('#theme-btn');
  if(button){button.textContent=next==='midnight'?'☾':next==='mist'?'◐':'☼';button.title='Сменить тему'}
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content',next==='midnight'?'#151a24':next==='mist'?'#f1f5fa':'#fffaf7');
  if(notify)toast(`Тема: ${{sunrise:'Тёплая',mist:'Спокойная',midnight:'Тёмная'}[next]}`);
}
applyTheme(localStorage.getItem('planner-theme')||'sunrise');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localParts=value=>{if(!value)return{date:'',time:''};let normalized=/Z$|[+-]\d\d:\d\d$/.test(value)?value:value+'Z',d=new Date(normalized);return{date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}};
const project=id=>S.projects.find(p=>p.id===id),column=(p,id)=>p?.columns?.find(c=>c.id===id),isoDate=t=>t.all_day?t.start_at?.slice(0,10)||'':localParts(t.start_at).date,isoTime=t=>t.all_day?'':localParts(t.start_at).time;
const liveTasks=()=>S.tasks.filter(t=>!t.archived_at);
const safeColor=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#5577e7';
function nextCalendarOccurrence(date,rule){
  let next=new Date(date),kind=(rule||'').replace(/^RRULE:/i,'').toUpperCase();
  kind=({DAILY:'FREQ=DAILY',WEEKDAYS:'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR',WEEKLY:'FREQ=WEEKLY',MONTHLY:'FREQ=MONTHLY',YEARLY:'FREQ=YEARLY'}[kind]||kind);let parts=Object.fromEntries(kind.split(';').map(x=>x.split('='))),interval=Math.max(1,+parts.INTERVAL||1),originalDay=next.getDate();
  if(parts.FREQ==='DAILY')next.setDate(next.getDate()+interval);
  else if(parts.FREQ==='WEEKLY'&&parts.BYDAY){let allowed=parts.BYDAY.split(',').map(x=>['SU','MO','TU','WE','TH','FR','SA'].indexOf(x)).filter(x=>x>=0),candidate=new Date(next);do{candidate.setDate(candidate.getDate()+1)}while(!allowed.includes(candidate.getDay()));next=candidate}
  else if(parts.FREQ==='WEEKLY')next.setDate(next.getDate()+7*interval);
  else if(parts.FREQ==='MONTHLY'){do{next.setDate(1);next.setMonth(next.getMonth()+interval)}while(new Date(next.getFullYear(),next.getMonth()+1,0).getDate()<originalDay);next.setDate(originalDay)}
  else if(parts.FREQ==='YEARLY'){let month=date.getMonth();do{next.setDate(1);next.setFullYear(next.getFullYear()+interval);next.setMonth(month)}while(new Date(next.getFullYear(),month+1,0).getDate()<originalDay);next.setDate(originalDay)}
  else return null;return next;
}
function calendarTasks(){let result=[];liveTasks().forEach(task=>{result.push(task);if(!task.start_at||!task.recurrence_rule||!task.deadline_at||['completed','cancelled'].includes(task.status))return;let start=new Date(task.start_at),deadline=new Date(task.deadline_at),endOffset=task.end_at?new Date(task.end_at)-start:null,current=start,count=1,rule=task.recurrence_rule.toUpperCase(),match=rule.match(/(?:^|;)COUNT=(\d+)/),max=match?+match[1]:1000;while(count<max){let next=nextCalendarOccurrence(current,rule);if(!next||next<=current||next>deadline)break;result.push({...task,start_at:next.toISOString(),end_at:endOffset===null?task.end_at:new Date(next.getTime()+endOffset).toISOString(),calendar_occurrence:true});current=next;count++}});return result}
const calendarEventStyle=t=>project(t.project_id)?`--project-color:${safeColor(project(t.project_id).color)}`:'';
const endTime=t=>{if(!t?.start_at||t.all_day)return'';let start=new Date(/Z$|[+-]\d\d:\d\d$/.test(t.start_at)?t.start_at:t.start_at+'Z'),value=t.end_at||t.due_at,end=value?new Date(/Z$|[+-]\d\d:\d\d$/.test(value)?value:value+'Z'):new Date(start.getTime()+(t.duration_minutes||0)*60000);return `${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`};
const fmt=(iso,opt={})=>new Intl.DateTimeFormat('ru-RU',opt).format(new Date((iso?.length===10?iso+'T12:00:00':iso)||Date.now()));
const localDateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const clockTime=(d=new Date())=>`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
const nowLine=kind=>`<div class="now-line now-line-${kind}" data-now-line="${kind}"${kind==='calendar'?` style="--now-minute:${new Date().getMinutes()}"`:''} aria-label="Текущее время ${clockTime()}"><span>${clockTime()}</span></div>`;
function updateCurrentTimeLines(){
  let now=new Date(),time=clockTime(now),calendar=$('[data-now-line="calendar"]');
  if(calendar){
    let target=$(`.cal-cell[data-date="${localDateKey(now)}"][data-time="${String(now.getHours()).padStart(2,'0')}:00"]`);
    if(target&&calendar.parentElement!==target)target.append(calendar);
    calendar.style.setProperty('--now-minute',now.getMinutes());calendar.querySelector('span').textContent=time;calendar.setAttribute('aria-label',`Текущее время ${time}`);
  }
  let schedule=$('[data-now-line="schedule"]');
  if(schedule){let target=$$('.timeline-item[data-schedule-time]').find(row=>row.dataset.scheduleTime>=time);target?schedule.parentElement.insertBefore(schedule,target):schedule.parentElement.append(schedule);schedule.querySelector('span').textContent=time;schedule.setAttribute('aria-label',`Текущее время ${time}`)}
}
function renderSchedule(items,date){
  let rows=items.map(t=>`<div class="timeline-item" data-schedule-time="${isoTime(t)}" style="--task-color:${project(t.project_id)?.color||'#5577e7'}"><div class="time">${isoTime(t)}</div><div class="rail"></div><div class="event" data-action="edit" data-id="${t.id}"><strong>${esc(t.title)}</strong><small>${esc(project(t.project_id)?.name||'Личное')}${t.location?' · '+esc(t.location):''}</small></div></div>`);
  if(date===localDateKey()){let at=items.findIndex(t=>isoTime(t)>=clockTime());rows.splice(at<0?rows.length:at,0,nowLine('schedule'))}
  return rows.join('')||'<div class="empty">Нет событий</div>';
}
const priorityLabel=value=>({P1:'Критично',P2:'Важно',P3:'Обычно',P4:'Не очень важно'}[value]||value);
const priorityOptions=value=>[['P1','Критично'],['P2','Важно'],['P3','Обычно'],['P4','Не очень важно']].map(([v,n])=>`<option value="${v}" ${v===(value||'P3')?'selected':''}>${n}</option>`).join('');
function fillTemplateOptions(form,selected=''){form.elements.template_choice.innerHTML='<option value="">Без шаблона</option><option value="__create__">Создать новый…</option>'+S.templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');form.elements.template_choice.value=selected}
const workflowStatuses=[['idea','Идеи'],['planned','Запланировано'],['in_progress','В работе'],['completed','Готово']];
const statusForColumn=name=>Object.fromEntries(workflowStatuses.map(([status,label])=>[label.toLowerCase(),status]))[name?.trim().toLowerCase()];
function fillWorkflowOptions(form,p,status='planned',columnId=''){let selected=columnId?`column:${columnId}`:`status:${status}`;form.elements.workflow.innerHTML=(p?.columns?.length?p.columns.map(c=>`<option value="column:${c.id}">${esc(c.name)}</option>`):workflowStatuses.map(([value,label])=>`<option value="status:${value}">${label}</option>`)).join('')+'<option value="status:cancelled">Отменено</option>';if(![...form.elements.workflow.options].some(o=>o.value===selected)&&p){let matching=p.columns.find(c=>statusForColumn(c.name)===status);selected=matching?`column:${matching.id}`:selected}form.elements.workflow.value=[...form.elements.workflow.options].some(o=>o.value===selected)?selected:form.elements.workflow.options[0]?.value||'status:planned'}
function updateTemplateActions(form){let selected=S.templates.some(t=>t.id===form.elements.template_choice.value);$('#edit-template').classList.toggle('hidden',!selected);$('#delete-template').classList.toggle('hidden',!selected)}
function toast(msg){let x=$('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2000)}
function heading(title,sub,extra=''){return `<div class="page-head"><div><span class="eyebrow">ЕЖЕДНЕВНИК</span><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`}
function taskRow(t){let p=project(t.project_id),deadline=localParts(t.deadline_at),claim=p&&!t.assigned_to_id&&!t.archived_at&&!['completed','cancelled'].includes(t.status),action=t.archived_at?'restore':['completed','cancelled'].includes(t.status)?'archive':claim?'assignself':'edit',label=t.archived_at?'Восстановить':['completed','cancelled'].includes(t.status)?'В архив':claim?'Назначить себе':'···';return `<div class="task-row ${t.status==='completed'?'completed':''} ${t.status==='cancelled'?'cancelled':''} ${t.postponed_at?'postponed':''} ${t.archived_at?'archived':''} ${t.is_overdue?'is-overdue':''}"><button class="check" data-action="taskstatus" data-id="${t.id}" aria-label="Выбрать результат задачи" title="Выполнить, отменить или перенести" ${t.archived_at?'disabled':''}>${t.status==='completed'?'✓':t.status==='cancelled'?'×':t.postponed_at?'↷':''}</button><div data-action="edit" data-id="${t.id}"><div class="task-name">${esc(t.title)}</div>${S.goals?.some(g=>g.id===t.goal_id)?`<small>Цель: ${esc(S.goals.find(g=>g.id===t.goal_id).title)}</small>`:""}<div class="meta"><span class="priority ${t.priority}">${priorityLabel(t.priority)}</span>${t.assignee?`<span>Исполнитель: ${esc(t.assignee.name)}</span>`:''}${t.archived_at?'<span>Архив</span>':''}${t.status==='cancelled'?'<span>Отменено</span>':''}${t.postponed_at?`<span class="postponed-meta">↷ ${t.start_at?'Перенесено':'На потом'}</span>`:''}${isoDate(t)?`<span>▦ ${fmt(isoDate(t),{day:'numeric',month:'short'})}</span>`:''}${isoTime(t)?`<span>◷ ${isoTime(t)}</span>`:''}${deadline.date?`<span class="deadline-meta">⚑ ${fmt(deadline.date,{day:'numeric',month:'short'})}${deadline.time?' '+deadline.time:''}</span>`:''}${p?`<span class="pill"><i class="dot" style="display:inline-block;background:${p.color}"></i> ${esc(p.name)}</span>`:''}</div></div><button class="icon-btn task-archive-action ${claim?'claim-task':''}" data-action="${action}" data-id="${t.id}">${label}</button></div>`}
function renderToday(){let d=viewDate.toISOString().slice(0,10),tasks=liveTasks(),later=tasks.filter(t=>t.postponed_at&&!t.start_at&&!['completed','cancelled'].includes(t.status)),items=tasks.filter(t=>isoDate(t)===d&&!['completed','cancelled'].includes(t.status)),timed=items.filter(t=>isoTime(t)).sort((a,b)=>isoTime(a).localeCompare(isoTime(b))),free=[...later,...items.filter(t=>!isoTime(t)&&!t.postponed_at)],late=d===today()?tasks.filter(t=>t.is_overdue):[],done=tasks.filter(t=>isoDate(t)===d&&t.status==='completed').length,total=items.length+done;return heading(d===today()?'Сегодня':fmt(d,{day:'numeric',month:'long'}),fmt(d,{weekday:'long',day:'numeric',month:'long'}),`<div class="date-nav"><button data-action="day" data-step="-1">‹</button><button data-action="today">Сегодня</button><button data-action="day" data-step="1">›</button></div>`)+`<div class="stats"><div class="stat"><strong>${items.length}</strong><small>задач</small></div><div class="stat"><strong>${(timed.reduce((s,t)=>s+t.duration_minutes,0)/60).toFixed(1).replace('.0','')}ч</strong><small>запланировано</small></div><div class="stat"><strong>${total?Math.round(done/total*100):0}%</strong><small>выполнено</small></div></div><div class="dashboard"><section class="card"><div class="card-title"><span>Расписание</span><b>${timed.length}</b></div>${renderSchedule(timed,d)}</section><div><section class="card ${later.length?'postponed-card':''}"><div class="card-title"><span>Без даты и на потом</span><b>${free.length}</b></div>${later.length?'<p class="postponed-hint">Задачи с пометкой «На потом» ждут новой даты.</p>':''}${free.map(taskRow).join('')||'<div class="empty">Всё запланировано</div>'}<form class="quick" id="quick"><input name="title" required placeholder="Добавить задачу…"><button class="primary">＋</button></form></section>${late.length?`<section class="card overdue" style="margin-top:18px"><div class="card-title"><span>Просрочено</span><b>${late.length}</b></div>${late.map(taskRow).join('')}</section>`:''}</div></div>`}
function renderTasks(inbox=false){let a=[...S.tasks,...S.archived].filter(t=>taskFilter==='archive'?!!t.archived_at:!t.archived_at).filter(t=>inbox?!t.start_at:true).filter(t=>!query||[t.title,t.description,t.location,(t.tags||[]).join(' '),project(t.project_id)?.name].join(' ').toLowerCase().includes(query));if(taskFilter==='active')a=a.filter(t=>!['completed','cancelled'].includes(t.status));if(taskFilter==='done')a=a.filter(t=>t.status==='completed');if(taskFilter==='cancelled')a=a.filter(t=>t.status==='cancelled');let rank={P1:1,P2:2,P3:3,P4:4};a.sort(taskSort==='priority'?(x,y)=>rank[x.priority]-rank[y.priority]:(x,y)=>(x.start_at||'z').localeCompare(y.start_at||'z'));return heading(inbox?'Входящие':'Все задачи',inbox?'Ещё не запланированы':'Поиск и комбинируемые фильтры',`<button class="primary" data-action="add">＋ Новая задача</button>`)+`<div class="toolbar"><div class="segmented">${[['all','Все'],['active','Активные'],['done','Готово'],['cancelled','Отменено'],['archive','Архив']].map(([v,n])=>`<button data-action="filter" data-value="${v}" class="${taskFilter===v?'active':''}">${n}</button>`).join('')}</div><select class="filter" id="task-sort"><option value="date">По дате</option><option value="priority" ${taskSort==='priority'?'selected':''}>По приоритету</option></select></div><section class="card">${a.map(taskRow).join('')||'<div class="empty">Ничего не найдено</div>'}</section>`}
function renderCalendar(){let tasks=calendarTasks(),sourceTasks=S.tasks;S.tasks=tasks;
  let selected=viewDate.toISOString().slice(0,10),controls=`<div style="display:flex;gap:8px;flex-wrap:wrap"><div class="date-nav"><button data-action="calnav" data-step="-1">‹</button><button data-action="today">Сегодня</button><button data-action="calnav" data-step="1">›</button></div><div class="segmented">${[['day','День'],['week','Неделя'],['month','Месяц'],['agenda','Повестка']].map(([v,n])=>`<button data-action="calmode" data-value="${v}" class="${calMode===v?'active':''}">${n}</button>`).join('')}</div>${calMode==='day'?`<button class="primary" data-action="adddate" data-date="${selected}">＋ Добавить</button>`:''}</div>`,body='';
  if(calMode==='month'){let y=viewDate.getFullYear(),m=viewDate.getMonth(),f=new Date(y,m,1),start=new Date(y,m,1-(f.getDay()||7)+1);body='<div class="month-grid">'+Array.from({length:42},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let iso=d.toISOString().slice(0,10),it=tasks.filter(t=>isoDate(t)===iso);return `<div class="month-day ${d.getMonth()!==m?'muted':''} ${iso===today()?'today':''}" data-date="${iso}"><button class="calendar-day-link" data-action="openday" data-date="${iso}">${d.getDate()}</button>${it.map(t=>`<div class="month-event priority-event ${t.priority} ${t.project_id?'project-colored':''}" style="${calendarEventStyle(t)}" draggable="true" data-drag="${t.id}" data-action="edit" data-id="${t.id}"><b>${t.priority}</b> ${isoTime(t)||'Весь день'} ${esc(t.title)}</div>`).join('')}</div>`}).join('')+'</div>'}
  else if(calMode==='agenda'){body=`<section class="card">${tasks.filter(t=>t.start_at&&isoDate(t)>=selected).sort((a,b)=>a.start_at.localeCompare(b.start_at)).map(taskRow).join('')}</section>`}
  else{let days=calMode==='day'?[new Date(viewDate)]:Array.from({length:7},(_,i)=>{let d=new Date(viewDate);d.setDate(d.getDate()-((d.getDay()+6)%7)+i);return d}),hours=Array.from({length:14},(_,i)=>i+7),now=new Date();body=`<div class="calendar-wrap"><div class="calendar-grid" style="grid-template-columns:54px repeat(${days.length},1fr)"><div class="cal-head"></div>${days.map(d=>{let iso=d.toISOString().slice(0,10);return `<div class="cal-head ${iso===localDateKey()?'today':''}"><button class="calendar-day-link" data-action="openday" data-date="${iso}">${fmt(iso,{weekday:'short',day:'numeric'})}</button></div>`}).join('')}${hours.map(h=>`<div class="cal-time">${String(h).padStart(2,'0')}:00</div>${days.map(d=>{let day=d.toISOString().slice(0,10),it=S.tasks.filter(t=>isoDate(t)===day&&+isoTime(t).slice(0,2)===h),marker=day===localDateKey()&&h===now.getHours()?nowLine('calendar'):'';return `<div class="cal-cell" data-date="${day}" data-time="${String(h).padStart(2,'0')}:00">${marker}${it.map(t=>`<div class="cal-event priority-event ${t.priority}" style="height:${Math.max(26,Math.round((t.duration_minutes||30)/60*58-5))}px" draggable="true" data-drag="${t.id}" data-action="edit" data-id="${t.id}"><b>${t.priority}</b> ${isoTime(t)}–${endTime(t)} ${esc(t.title)}</div>`).join('')}</div>`}).join('')}`).join('')}</div></div>`}
  S.tasks=sourceTasks;return heading('Календарь',fmt(selected,{month:'long',year:'numeric'}),controls)+body
}
function decorateCalendar(){if(page!=='calendar')return;$$('.cal-event,.month-event').forEach(item=>{let task=S.tasks.find(t=>t.id===item.dataset.id),p=project(task?.project_id),shownDate=item.closest('[data-date]')?.dataset.date;if(shownDate&&shownDate!==isoDate(task)){item.draggable=false;item.removeAttribute('data-drag');item.title='Будущий повтор — изменяется через исходную задачу'}if(!p)return;item.classList.add('project-colored');item.style.setProperty('--project-color',safeColor(p.color))})}
function renderProjects(){let p=project(projectId)||S.projects[0];if(!p)return heading('Проекты','Создайте первый проект',`<button class="primary" data-action="newproject">＋ Проект</button>`);let details=`<span class="priority ${p.priority||'P3'}">${priorityLabel(p.priority||'P3')}</span>${p.team_label?` · <span class="team-tag">${esc(p.team_label)}</span>`:''}`;return heading('Проекты',`${esc(p.name)} · ${details}`,`<div><select class="filter" id="project-picker">${S.projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select> <button class="secondary" data-ui-action="addmember">＋ Участник</button> <button class="secondary" data-action="editproject">Изменить проект</button> <button class="primary" data-action="newproject">＋ Проект</button> <button class="secondary" data-action="newcolumn">＋ Колонка</button></div>`)+`<div class="kanban">${p.columns.map(c=>{let a=S.tasks.filter(t=>t.project_id===p.id&&t.column_id===c.id&&t.status!=='cancelled');return `<div class="kanban-col" data-column="${c.id}"><div class="col-head"><span>${esc(c.name)}</span><span>${a.length}</span></div>${a.map(t=>`<article class="kanban-card ${t.status==='completed'?'completed':''}" draggable="${t.status!=='completed'}" ${t.status!=='completed'?`data-drag="${t.id}"`:''} data-action="edit" data-id="${t.id}"><span class="priority ${t.priority}">${priorityLabel(t.priority)}</span><h4>${t.status==='completed'?'✓ ':''}${esc(t.title)}</h4><div class="meta">${isoDate(t)?fmt(isoDate(t),{day:'numeric',month:'short'}):''}</div></article>`).join('')}<button class="secondary" style="width:100%" data-action="addcolumn" data-column="${c.id}">＋ Задача</button></div>`}).join('')}</div>`}
function renderTemplates(){return heading('Шаблоны','Быстрое создание типовых задач',`<button class="primary" data-action="newtemplate">＋ Шаблон</button>`)+`<div class="template-grid">${S.templates.map(t=>`<article class="template-card"><div class="template-icon">${esc(t.icon)}</div><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><button class="secondary" data-action="usetemplate" data-id="${t.id}">Использовать</button></article>`).join('')}</div>`}
function renderSettings(){let current=document.body.dataset.theme||'sunrise',themeCards=[['sunrise','Тёплая','Светлая, воздушная, с коралловым акцентом'],['mist','Спокойная','Холодные серо-голубые оттенки'],['midnight','Тёмная','Комфортная тема для вечерней работы']].map(([id,name,desc])=>`<button class="theme-option ${current===id?'active':''}" type="button" data-theme-choice="${id}" aria-pressed="${current===id}"><span class="theme-preview ${id}"><i></i><i></i><i></i></span><span><strong>${name}</strong><small>${desc}</small></span><b>${current===id?'✓':''}</b></button>`).join('');return heading('Настройки','Внешний вид, аккаунт и интеграции')+`<section class="card appearance-card"><div class="card-title"><span>Оформление</span><small>Выбор сохраняется на этом устройстве</small></div><div class="theme-grid">${themeCards}</div></section><div class="project-grid settings-grid">${profileCard(S.user)}<section class="card"><div class="card-title">Google Calendar <b>не подключён</b></div><p>OAuth-адаптер подготовлен. Укажите GOOGLE_CLIENT_ID и GOOGLE_CLIENT_SECRET.</p><button class="primary" data-action="google">Подключить</button></section></div>`}
function renderSettingsWithArchive(){let base=renderSettings(),policy=S.user.completed_task_archive_policy||'never',options=[['never','Не архивировать автоматически'],['immediate','Сразу после завершения'],['end_of_day','В конце дня'],['after_days','Через указанное число дней']].map(([v,n])=>`<option value="${v}" ${policy===v?'selected':''}>${n}</option>`).join('');return base+`<section class="card archive-settings"><div class="card-title"><span>Архив завершённых задач</span><small>Архив можно открыть в разделе «Все задачи»</small></div><form id="archive-settings"><label>Когда переносить<select name="policy">${options}</select></label><label>Количество дней<input type="number" name="days" min="1" max="365" value="${S.user.completed_task_archive_days||7}"></label><button class="primary">Сохранить</button></form></section>`}
function payload(f){let date=f.date.value,time=f.time.value,endValue=f.end_time.value,allDay=!time,start=date?new Date(`${date}T${time||'12:00'}:00`):null,end=date&&time&&endValue?new Date(`${date}T${endValue}:00`):null,deadlineDate=f.deadline_date.value,deadlineTime=f.deadline_time.value,deadline=deadlineDate?new Date(`${deadlineDate}T${deadlineTime||'23:59:59'}`):null;if(end&&end<=start)throw new Error('Время окончания должно быть позже времени начала');let duration=end?Math.round((end-start)/60000):+f.duration.value,[kind,value]=f.workflow.value.split(':'),p=project(f.project.value),selectedColumn=kind==='column'?p?.columns.find(c=>c.id===value):null,status=selectedColumn?statusForColumn(selectedColumn.name)||'planned':value;return {...(!f.goal.disabled?{goal_id:f.goal.value||null}:{}),title:f.title.value.trim(),description:f.description.value,priority:f.priority.value,status,project_id:f.project.value||null,column_id:selectedColumn?.id||null,assigned_to_id:f.assignee.value||null,start_at:start?.toISOString()||null,end_at:end?.toISOString()||null,deadline_at:deadline?.toISOString()||null,deadline_action:f.deadline_action.value,duration_minutes:duration,all_day:allDay,location:f.location.value,tags:f.tags.value.split(',').map(x=>x.trim()).filter(Boolean),recurrence_rule:f.recurrence.value,reminder_offsets:f.reminder.value?[+f.reminder.value]:[]}}
function closeModal(){$('#modal').classList.add('hidden')}
document.addEventListener('click',async e=>{let button=e.target.closest('[data-action="taskstatus"]');if(!button)return;e.preventDefault();e.stopImmediatePropagation();let task=S.tasks.find(t=>t.id===button.dataset.id);if(!task)return;let result=await uiDialog('Что сделать с задачей?',`<label>Результат<select name="outcome"><option value="completed">Выполнено</option><option value="cancelled">Отменено</option><option value="postponed">Перенесено</option></select></label><div class="form-grid"><label>Новая дата<input name="date" type="date" min="${localDateKey()}"></label><label>Время<input name="time" type="time"></label></div><label class="check-label"><input type="checkbox" value="later"> Перенести на потом без даты</label><small>Дата и время используются только для результата «Перенесено».</small>`,'Применить');if(!result)return;try{let patch={sync_version:task.sync_version};if(result.outcome==='completed'||result.outcome==='cancelled'){patch.status=result.outcome;patch.postponed_at=null}else{let later=result.checked.includes('later');if(!later&&!result.date)throw new Error('Выберите дату или пункт «Перенести на потом»');patch.status='planned';patch.postponed_at=new Date().toISOString();patch.start_at=later?null:new Date(`${result.date}T${result.time||'12:00'}:00`).toISOString();patch.end_at=null;patch.all_day=later||!result.time}let updated=await api('/tasks/'+task.id,{method:'PATCH',body:JSON.stringify(patch)});S.tasks=S.tasks.map(t=>t.id===updated.id?updated:t);render();toast(result.outcome==='completed'?'Задача выполнена':result.outcome==='cancelled'?'Задача отменена':result.checked.includes('later')?'Задача перенесена на потом':'Задача перенесена')}catch(error){toast(error.message)}},true);
function bindDrag(){$$('[data-drag]').forEach(x=>x.ondragstart=e=>{dragTask=x.dataset.drag;e.stopPropagation()});$$('[data-column],[data-date]').forEach(x=>{x.ondragover=e=>e.preventDefault();x.ondrop=async e=>{e.preventDefault();e.stopPropagation();calendarDropUntil=Date.now()+500;let t=S.tasks.find(v=>v.id===dragTask);if(!t)return;let patch={sync_version:t.sync_version};if(x.dataset.column)patch.column_id=x.dataset.column;if(x.dataset.date)Object.assign(patch,calendarMovePatch(t,x.dataset.date,x.dataset.time||isoTime(t)));try{let updated=await api('/tasks/'+t.id,{method:'PATCH',body:JSON.stringify(patch)});S.tasks=S.tasks.map(v=>v.id===t.id?updated:v);dragTask=null;render();toast('Дата и время задачи обновлены')}catch(error){dragTask=null;toast(error.message)}}})}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-page]');if(b){page=b.dataset.page;$('#sidebar').classList.remove('open');render();return}b=e.target.closest('[data-action]');if(!b)return;let t=[...S.tasks,...S.archived].find(x=>x.id===b.dataset.id);try{switch(b.dataset.action){case'add':openTask();break;case'edit':openTask(t);break;case'complete':{let u=await api('/tasks/'+t.id,{method:'PATCH',body:JSON.stringify({status:t.status==='completed'?'planned':'completed',sync_version:t.sync_version})});S.tasks=S.tasks.map(x=>x.id===u.id?u:x);render();break}case'filter':taskFilter=b.dataset.value;render();break;case'day':viewDate.setDate(viewDate.getDate()+ +b.dataset.step);render();break;case'today':viewDate=new Date();render();break;case'calnav':viewDate.setDate(viewDate.getDate()+(calMode==='month'?30:calMode==='week'?7:1)*+b.dataset.step);render();break;case'calmode':calMode=b.dataset.value;render();break;case'sideproject':projectId=b.dataset.id;page='projects';$('#sidebar').classList.remove('open');render();break;case'addcolumn':openTask({}, {project_id:projectId,column_id:b.dataset.column,date:''});break;case'usetemplate':{let x=S.templates.find(v=>v.id===b.dataset.id);openTask({title:x.name,duration_minutes:x.duration,priority:x.priority,location:x.location,project_id:x.project_id,reminder_offsets:x.reminders});break}case'newproject':{let name=prompt('Название проекта');if(name){let p=await api('/projects',{method:'POST',body:JSON.stringify({name,color:'#5577e7'})});S.projects.push(p);projectId=p.id;render()}break}case'newcolumn':{let name=prompt('Название колонки');if(name){let c=await api(`/projects/${projectId}/columns`,{method:'POST',body:JSON.stringify({name})});project(projectId).columns.push(c);render()}break}case'newtemplate':{let name=prompt('Название шаблона');if(name){let x=await api('/templates',{method:'POST',body:JSON.stringify({name,description:'60 минут · P3'})});S.templates.push(x);render()}break}case'logout':await api('/auth/logout',{method:'POST'});location.reload();break;case'google':toast('Добавьте Google OAuth credentials на сервере');break}}catch(x){toast(x.message)}});
$('#task-form').addEventListener('submit',saveTask);$$('[data-close]').forEach(x=>x.onclick=closeModal);$('#delete-task').onclick=async()=>{let id=$('#task-form').id.value;if(!id||!confirm('Удалить задачу?'))return;await api('/tasks/'+id,{method:'DELETE'});S.tasks=S.tasks.filter(x=>x.id!==id);closeModal();render();toast('Задача удалена')};$('#menu-btn').onclick=()=>$('#sidebar').classList.toggle('open');$('#theme-btn').onclick=()=>{let current=document.body.dataset.theme||'sunrise';applyTheme(themes[(themes.indexOf(current)+1)%themes.length],true);if(page==='settings')render()};$('.avatar').onclick=()=>{page='settings';render()};$('#search').oninput=e=>{query=e.target.value.toLowerCase();if(query)page='tasks';render()};document.addEventListener('click',e=>{let choice=e.target.closest('[data-theme-choice]');if(!choice)return;applyTheme(choice.dataset.themeChoice,true);render()});document.addEventListener('change',e=>{if(e.target.id==='task-sort'){taskSort=e.target.value;render()}if(e.target.id==='project-picker'){projectId=e.target.value;render()}});document.addEventListener('click',e=>{if(page!=='calendar'||Date.now()<calendarDropUntil||e.target.closest('[data-action],.cal-event,.month-event'))return;let c=e.target.closest('.cal-cell,.month-day');if(c)openTask({}, {date:c.dataset.date,time:c.dataset.time||''})});
document.addEventListener('change',e=>{let f=e.target.closest('#task-form');if(!f||e.target.name!=='project')return;let p=project(f.elements.project.value);fillTaskPeople(f,p);fillWorkflowOptions(f,p,'planned')},true);
$('#auth-switch').onclick=()=>{authRegister=!authRegister;$('#auth-title').textContent=authRegister?'Создать аккаунт':'Войти в ежедневник';$('#auth-submit').textContent=authRegister?'Зарегистрироваться':'Войти';$('#auth-switch').textContent=authRegister?'Уже есть аккаунт? Войти':'Нет аккаунта? Зарегистрироваться';$('.register-only').classList.toggle('hidden',!authRegister)};$('#auth-form').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(!d.nickname)delete d.nickname;try{await api('/auth/'+(authRegister?'register':'login'),{method:'POST',body:JSON.stringify(d)});await load()}catch(x){$('#auth-error').textContent=x.message}};
load().then(startRealtime).catch(()=>{$('#auth-screen').classList.remove('hidden')});

function fillTaskPeople(f,p,selected=''){let people=p?.members||[{user_id:S.user.id,name:S.user.name,nickname:S.user.nickname}];f.elements.assignee.innerHTML='<option value="">Не назначен</option>'+people.map(m=>`<option value="${m.user_id}">${esc(m.name)}${m.nickname?` (@${esc(m.nickname)})`:''}</option>`).join('');f.elements.assignee.value=selected||''}
function openTask(t={},preset={}){let f=$('#task-form'),x={...preset,...t},deadline=localParts(x.deadline_at);f.reset();f.elements.goal.innerHTML=goalOptions(S.goals,x.goal_id);f.elements.goal.disabled=!!x.user_id&&x.user_id!==S.user.id;updateGoalHint();delete f.dataset.templateName;fillTemplateOptions(f,preset.templateChoice||'');updateTemplateActions(f);f.elements.id.value=x.id||'';f.elements.title.value=x.title||'';f.elements.date.value=isoDate(x)||preset.date||viewDate.toISOString().slice(0,10);f.elements.time.value=isoTime(x)||preset.time||'';f.elements.end_time.value=endTime(x);f.elements.deadline_date.value=deadline.date;f.elements.deadline_time.value=deadline.time==='23:59'?'':deadline.time;f.elements.deadline_action.value=x.deadline_action||'none';f.elements.duration.value=x.duration_minutes||60;f.elements.priority.value=x.priority||'P3';f.elements.project.value=x.project_id||preset.project_id||'';let p=project(f.elements.project.value);fillWorkflowOptions(f,p,x.status||'planned',x.column_id||preset.column_id||'');fillTaskPeople(f,p,x.assigned_to_id);f.elements.location.value=x.location||'';f.elements.description.value=x.description||'';f.elements.tags.value=(x.tags||[]).join(', ');f.elements.recurrence.value=x.recurrence_rule||'';f.elements.reminder.value=x.reminder_offsets?.[0]||'';$('#delete-task').classList.toggle('hidden',!x.id);$('#modal').classList.remove('hidden')}
async function saveTask(e){e.preventDefault();let f=e.target,id=f.elements.id.value;try{let data=payload(f);if(f.dataset.templateName){let template=await api('/templates',{method:'POST',body:JSON.stringify({name:f.dataset.templateName,description:data.description,duration:data.duration_minutes,priority:data.priority,location:data.location,project_id:data.project_id,reminders:data.reminder_offsets,task_data:data})});S.templates.push(template)}let t=id?await api('/tasks/'+id,{method:'PATCH',body:JSON.stringify({...data,sync_version:S.tasks.find(x=>x.id===id)?.sync_version})}):await api('/tasks',{method:'POST',body:JSON.stringify(data)});S.tasks=id?S.tasks.map(x=>x.id===id?t:x):[...S.tasks,t];closeModal();render();toast(f.dataset.templateName?'Шаблон и задача сохранены':id?'Задача обновлена':'Задача создана')}catch(x){toast(x.message)}}
$('#delete-task').onclick=async()=>{let id=$('#task-form').elements.id.value;if(!id||!confirm('Удалить задачу?'))return;await api('/tasks/'+id,{method:'DELETE'});S.tasks=S.tasks.filter(x=>x.id!==id);closeModal();render();toast('Задача удалена')};
$('#edit-template').onclick=async()=>{let f=$('#task-form'),id=f.elements.template_choice.value,current=S.templates.find(t=>t.id===id);if(!current)return;let result=await uiDialog('Редактировать шаблон',`<label>Название шаблона<input name="name" required value="${esc(current.name)}"></label>`);if(!result)return;try{let data=payload(f),updated=await api(`/templates/${id}`,{method:'PATCH',body:JSON.stringify({name:result.name.trim(),icon:current.icon||'✦',description:data.description,duration:data.duration_minutes,priority:data.priority,location:data.location,project_id:data.project_id,reminders:data.reminder_offsets,task_data:data})});S.templates=S.templates.map(t=>t.id===id?updated:t);fillTemplateOptions(f,id);updateTemplateActions(f);toast('Шаблон обновлён')}catch(error){toast(error.message)}};
$('#delete-template').onclick=async()=>{let f=$('#task-form'),id=f.elements.template_choice.value,current=S.templates.find(t=>t.id===id);if(!current||!confirm(`Удалить шаблон «${current.name}»?`))return;try{await api(`/templates/${id}`,{method:'DELETE'});S.templates=S.templates.filter(t=>t.id!==id);fillTemplateOptions(f,'');updateTemplateActions(f);toast('Шаблон удалён')}catch(error){toast(error.message)}};
let resizeState=null;document.addEventListener('pointerdown',e=>{let el=e.target.closest('.cal-event');if(!el)return;let r=el.getBoundingClientRect();if(e.clientY<r.bottom-8)return;let task=S.tasks.find(x=>x.id===el.dataset.id);if(!task)return;e.preventDefault();e.stopPropagation();resizeState={task,startY:e.clientY,el};el.classList.add('resizing')},true);document.addEventListener('pointermove',e=>{if(resizeState)resizeState.el.style.height=Math.max(20,resizeState.el.offsetHeight+e.movementY)+'px'});document.addEventListener('pointerup',async e=>{if(!resizeState)return;let {task,startY,el}=resizeState,delta=Math.round((e.clientY-startY)/15)*15,duration=Math.max(15,task.duration_minutes+delta);resizeState=null;el.classList.remove('resizing');let updated=await api('/tasks/'+task.id,{method:'PATCH',body:JSON.stringify({duration_minutes:duration,sync_version:task.sync_version})});S.tasks=S.tasks.map(x=>x.id===updated.id?updated:x);render();toast(`Длительность: ${duration} мин`)},true);

const plannerRender=render;
render=function(){if(page!=='finance'){plannerRender();if(page==='goals')$$('.goal-card').forEach((card,i)=>{let g=S.goals.filter(x=>x.period===goalPeriod&&x.period_start<=goalDate&&x.period_end>=goalDate)[i];if(!g?.target_amount)return;card.querySelector('.goal-why')?.insertAdjacentHTML('afterend',`<div class="financial-goal"><b>${Number(g.financial_current).toLocaleString('ru-RU')} ${g.currency} / ${Number(g.target_amount).toLocaleString('ru-RU')} ${g.currency}</b><progress max="100" value="${g.financial_progress}"></progress><span>${g.financial_progress}% накоплено</span></div>`) });return}if(!S.user)return;$('#content').innerHTML=renderFinance(S);$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page))};
const plannerPayload=payload;
payload=function(f){let data=plannerPayload(f);if(f.elements.finance_enabled.checked){let account=S.financeAccounts.find(a=>a.id===f.elements.finance_account.value);if(!account)throw new Error('Выберите финансовый счёт');data.finance={type:f.elements.finance_type.value,amount:f.elements.finance_amount.value,currency:account.currency,account_id:account.id,category_id:f.elements.finance_category.value||null}}else data.finance=null;return data};
const plannerOpenTask=openTask;
openTask=function(t={},preset={}){plannerOpenTask(t,preset);let f=$('#task-form'),binding=S.financePlanned?.find(x=>x.task_id===(t.id||preset.id));f.elements.finance_account.innerHTML=(S.financeAccounts||[]).map(a=>`<option value="${a.id}">${esc(a.name)} · ${a.currency}</option>`).join('');f.elements.finance_category.innerHTML='<option value="">Без категории</option>'+(S.financeCategories||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');f.elements.finance_enabled.checked=!!binding;f.elements.finance_type.value=binding?.type||'expense';f.elements.finance_amount.value=binding?.amount||'';f.elements.finance_account.value=binding?.account_id||S.financeAccounts?.[0]?.id||'';f.elements.finance_category.value=binding?.category_id||'';f.querySelector('.task-finance').open=!!binding};

let activeChannel=null,chatMessages=[];
function renderContacts(){let search=`<div style="display:flex;gap:8px;flex-wrap:wrap"><form class="friend-search" id="friend-search"><input name="nickname" required minlength="2" autocomplete="off" placeholder="Введите ник, например ocean_dev"><button class="primary">Найти</button></form><button class="secondary" data-ui-action="friendroles">Настроить роли</button></div>`,requests=S.friendRequests.length?`<section class="card friend-requests"><div class="card-title">Запросы в друзья <b>${S.friendRequests.length}</b></div>${S.friendRequests.map(x=>`<div class="friend-request"><div class="contact-avatar">${esc(x.name.slice(0,2).toUpperCase())}</div><div><strong>${esc(x.name)}</strong><small>@${esc(x.nickname||'пользователь')} хочет добавить вас в друзья</small></div><button class="primary" data-friend-request="accept" data-id="${x.id}">Принять</button><button class="secondary" data-friend-request="reject" data-id="${x.id}">Отклонить</button></div>`).join('')}</section>`:'',results=friendResults.length?`<section class="card friend-results"><div class="card-title">Результаты поиска</div>${friendResults.map(x=>`<div class="friend-result"><div><b>${esc(x.name)}</b><div class="meta">@${esc(x.nickname)}</div></div>${x.is_friend?'<span class="team-tag">Уже в друзьях</span>':`<button class="secondary" data-friend-add="${esc(x.nickname)}">Добавить</button>`}</div>`).join('')}</section>`:'';return heading('Друзья','Найдите пользователя по нику и отправьте запрос',search)+requests+results+`<div class="contacts-grid">${S.contacts.map(c=>`<article class="contact-card"><div style="display:flex;gap:12px;align-items:center"><div class="contact-avatar">${esc(c.name.slice(0,2).toUpperCase())}</div><div><b>${esc(c.nickname||c.name)}</b><div class="meta">@${esc(c.user_nickname||'пользователь')}</div><div class="tag-row">${(c.roles||[]).map(r=>`<span class="team-tag" style="border-color:${r.color};color:${r.color}">${esc(r.name)}</span>`).join('')||(c.tags||[]).map(t=>`<span class="team-tag">${esc(t)}</span>`).join('')||'<span class="meta">Роли не назначены</span>'}</div></div></div><button class="icon-btn" data-team-action="editcontact" data-id="${c.id}" title="Настроить друга">⚙</button></article>`).join('')||'<div class="empty">Подтверждённых друзей пока нет</div>'}</div>`}
function renderTeam(){
  let p=project(projectId)||S.projects[0];if(!p)return heading('Команда','Сначала создайте проект');if(!activeChannel||!p.channels.some(c=>c.id===activeChannel))activeChannel=p.channels[0]?.id||null;
  let channel=p.channels.find(c=>c.id===activeChannel),projectTasks=S.tasks.filter(t=>t.project_id===p.id&&!['completed','cancelled'].includes(t.status)),channels=p.channels.map(c=>`<div class="channel-row ${c.id===activeChannel?'active':''}"><button class="channel-btn" data-team-action="channel" data-id="${c.id}"># ${esc(c.name)}</button><button class="channel-menu" data-ui-action="channelmenu" data-id="${c.id}" aria-label="Настроить канал ${esc(c.name)}">⋯</button></div>`).join('');
  return heading('Команда',`Проект ${esc(p.name)} · ${p.team_label?`ярлык <span class="team-tag">${esc(p.team_label)}</span>`:'ярлык не задан'}`,`<select class="filter" id="team-project">${S.projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button class="secondary" data-team-action="teamlabel">Ярлык команды</button>`)+`<div class="team-layout"><aside class="channel-list"><h3>КАНАЛЫ</h3>${channels}<button class="channel-btn" data-team-action="newchannel">＋ Канал</button></aside><section class="chat-main"><div class="chat-head"># ${esc(channel?.name||'канал')}</div><div class="messages" id="messages">${chatMessages.map(m=>`<div class="message"><div class="message-avatar">${esc(m.author.name.slice(0,2).toUpperCase())}</div><div><span class="message-author">${esc(m.author.name)}</span><span class="message-time">${fmt(m.created_at,{hour:'2-digit',minute:'2-digit'})}</span><div class="message-content">${esc(m.content)}</div>${m.task?`<div class="attached-task"><span class="priority ${m.task.priority}">${m.task.priority}</span> <b>${esc(m.task.title)}</b><div class="meta">Прикреплено из Kanban</div></div>`:''}</div></div>`).join('')||'<div class="empty">Начните обсуждение проекта</div>'}</div><form class="chat-form" id="chat-form"><textarea name="content" rows="2" placeholder="Написать в #${esc(channel?.name||'канал')}"></textarea><select class="filter" name="task"><option value="">Без задачи</option>${projectTasks.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select><button class="primary">Отправить</button></form></section><aside class="member-list"><h3>УЧАСТНИКИ — ${p.members.length}</h3>${p.members.map(m=>`<div class="member"><span class="role-dot" style="background:${m.role_color}"></span><div><b>${esc(m.name)}</b><div class="meta">${(m.roles||[{name:m.role}]).map(r=>esc(r.name)).join(', ')} <button type="button" data-team-action="role" data-member="${m.id}" title="Изменить роли">⚙</button></div></div></div>`).join('')}<button class="secondary" style="width:100%;margin-top:12px" data-team-action="addmember">＋ Участник</button><button class="secondary" style="width:100%;margin-top:8px" data-team-action="newrole">＋ Роль</button></aside></div>`
}
function decorateTeam(){if(page!=='team')return;let p=project(projectId),add=document.querySelector('[data-team-action="addmember"]');if(add){add.textContent='＋ Участник из друзей';add.insertAdjacentHTML('afterend','<button class="secondary" style="width:100%;margin-top:8px" data-ui-action="projectrules">Права ролей проекта</button>')}p?.members.forEach(m=>{let gear=document.querySelector(`[data-team-action="role"][data-member="${m.id}"]`),meta=gear?.parentElement;if(meta&&m.nickname)meta.insertAdjacentText('afterbegin',`@${m.nickname} · `);if(meta&&m.is_owner){meta.insertAdjacentText('beforeend',' · администратор проекта');gear.remove()}})}
function render(){if(!S.user)return;let html=page==='today'?renderToday():page==='calendar'?renderCalendar():page==='tasks'?renderTasks():page==='inbox'?renderTasks(true):page==='ai'?renderAI(S.user):page==='goals'?renderGoals(S,taskRow,goalPeriod,goalDate):page==='projects'?renderProjects():page==='templates'?renderTemplates():page==='team'?renderTeam():page==='contacts'?renderContacts():renderSettingsWithArchive();$('#content').innerHTML=html;$('#today-count').textContent=S.tasks.filter(t=>isoDate(t)===today()&&!['completed','cancelled'].includes(t.status)).length;$('#inbox-count').textContent=S.tasks.filter(t=>!t.start_at&&!['completed','cancelled'].includes(t.status)).length;let requestCount=S.friendRequests.length,badge=$('#friend-request-count'),alert=$('#friends-alert');badge.textContent=requestCount;badge.classList.toggle('hidden',!requestCount);alert.classList.toggle('hidden',!requestCount);alert.textContent=`♢ ${requestCount}`;$('#side-projects').innerHTML=S.projects.map(p=>`<button class="project-link" data-action="sideproject" data-id="${p.id}"><i class="dot" style="background:${p.color}"></i>${esc(p.name)}</button>`).join('');$('#project-select').innerHTML='<option value="">Без проекта</option>'+S.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');bindDrag();decorateTeam();decorateCalendar();updateCurrentTimeLines();if(page==='team'&&activeChannel)loadMessages(false)}
async function load(){let [user,projects,allTasks,templates,contacts,friendRequests,friendRoles,notifications,goals,financeAccounts,financeCategories,financeTransactions,financeAnalytics,financePlanned]=await Promise.all([api('/auth/me'),api('/projects'),api('/tasks?include_archived=true'),api('/templates'),api('/contacts'),api('/friend-requests'),api('/friend-roles'),api('/notifications/feed'),api('/goals'),api('/finance/accounts'),api('/finance/categories'),api('/finance/transactions'),api('/finance/analytics'),api('/finance/planned')]),tasks=allTasks.filter(t=>!t.archived_at),archived=allTasks.filter(t=>t.archived_at);Object.assign(S,{user,projects,tasks,archived,templates,contacts,friendRequests,friendRoles,notifications,goals,financeAccounts,financeCategories,financeTransactions,financeAnalytics,financePlanned});projectId=projects[0]?.id;$('#auth-screen').classList.add('hidden');render()}
async function refreshRealtime(){if(realtimeRefresh)return realtimeRefresh;realtimeRefresh=(async()=>{try{let [projects,allTasks,templates,contacts,friendRequests,friendRoles,notifications,goals]=await Promise.all([api('/projects'),api('/tasks?include_archived=true'),api('/templates'),api('/contacts'),api('/friend-requests'),api('/friend-roles'),api('/notifications/feed'),api('/goals')]);S.goals=goals;S.projects=projects;S.tasks=allTasks.filter(t=>!t.archived_at);S.archived=allTasks.filter(t=>t.archived_at);S.templates=templates;S.contacts=contacts;S.friendRequests=friendRequests;S.friendRoles=friendRoles;S.notifications=notifications;if(projectId&&!projects.some(p=>p.id===projectId))projectId=projects[0]?.id||null;if(activeChannel&&!projects.some(p=>p.channels?.some(c=>c.id===activeChannel)))activeChannel=null;if(activeChannel)await loadMessages(false);render()}catch(x){if(!String(x.message).includes('авторизация'))console.warn('Не удалось обновить данные',x)}finally{realtimeRefresh=null}})();return realtimeRefresh}
function startRealtime(){if(realtimeSource)realtimeSource.close();realtimeSource=new EventSource('/api/v1/events');realtimeSource.addEventListener('change',()=>refreshRealtime());realtimeSource.onerror=()=>{};window.addEventListener('beforeunload',()=>realtimeSource?.close(),{once:true})}
const projectDeleteObserver=new MutationObserver(()=>{if(page!=='projects'||!projectId||$('#project-delete'))return;let picker=$('#project-picker');if(!picker)return;let button=document.createElement('button');button.id='project-delete';button.className='danger';button.dataset.action='deleteproject';button.textContent='Удалить проект';picker.parentElement.append(' ',button)});projectDeleteObserver.observe($('#content'),{childList:true,subtree:true});
const claimTaskObserver=new MutationObserver(()=>{if(page!=='projects'||!projectId)return;S.tasks.filter(t=>t.project_id===projectId&&!t.assigned_to_id&&!['completed','cancelled'].includes(t.status)).forEach(t=>{let card=$(`.kanban-card[data-id="${t.id}"]`);if(!card||card.querySelector('[data-action="assignself"]'))return;card.insertAdjacentHTML('beforeend',`<button class="secondary claim-kanban" data-action="assignself" data-id="${t.id}">Назначить себе</button>`)})});claimTaskObserver.observe($('#content'),{childList:true,subtree:true});
const notificationSettingsObserver=new MutationObserver(()=>{if(page!=='settings'||$('#notification-settings'))return;let labels={friend_incoming:'Входящая заявка в друзья',friend_outgoing:'Статус заявки в друзья',task_assigned:'Вас назначили исполнителем',task_self_assigned:'Участник назначил себя',deadline_soon:'Дедлайн через 15 минут',urgent_task:'Срочная задача P1'},rules=S.user.notification_settings||{},rows=Object.entries(labels).map(([event,label])=>{let rule=rules[event]||{enabled:true,channel:'bell',priority:'normal'};return `<div class="notification-rule" data-event="${event}"><label class="check-label"><input name="enabled" type="checkbox" ${rule.enabled?'checked':''}> ${label}</label><select name="channel"><option value="bell" ${rule.channel==='bell'?'selected':''}>Колокольчик</option><option value="sound" ${rule.channel==='sound'?'selected':''}>Звук</option><option value="alarm" ${rule.channel==='alarm'?'selected':''}>Будильник</option></select><select name="priority"><option value="normal" ${rule.priority==='normal'?'selected':''}>Обычный</option><option value="high" ${rule.priority==='high'?'selected':''}>Высокий</option><option value="urgent" ${rule.priority==='urgent'?'selected':''}>Срочный</option></select></div>`}).join('');$('#content').insertAdjacentHTML('beforeend',`<section class="card notification-settings-card"><div class="card-title"><span>Уведомления</span><small>Событие → канал → приоритет → поведение</small></div><form id="notification-settings">${rows}<button class="primary">Сохранить настройки</button></form></section>`)});notificationSettingsObserver.observe($('#content'),{childList:true,subtree:true});
async function loadMessages(redraw=true){if(!activeChannel)return;try{chatMessages=await api(`/channels/${activeChannel}/messages`);if(redraw&&page==='team')render();else{let box=$('#messages');if(box)box.scrollTop=box.scrollHeight}}catch(e){}}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-team-action="addcontact"],[data-team-action="addmember"]');if(!b)return;e.stopImmediatePropagation();try{if(b.dataset.teamAction==='addcontact'){let q=prompt('Ник пользователя в приложении');if(!q)return;let found=await api(`/users/search?q=${encodeURIComponent(q)}`),person=found.find(x=>x.nickname.toLowerCase()===q.trim().toLowerCase())||found[0];if(!person)return toast('Пользователь не найден');if(person.is_friend)return toast('Этот пользователь уже в друзьях');let tags=prompt(`Добавить @${person.nickname} в друзья. Теги команд через запятую:`,'');let c=await api('/contacts',{method:'POST',body:JSON.stringify({user_nickname:person.nickname,tags:(tags||'').split(',').map(x=>x.trim()).filter(Boolean)})});S.contacts.push(c);render();toast('Пользователь добавлен в друзья')}else{let p=project(projectId),list=S.contacts.map(c=>`@${c.user_nickname}`).join(', '),nick=prompt(`Ник участника из друзей:\n${list}`);if(!nick)return;let friend=S.contacts.find(c=>(c.user_nickname||'').toLowerCase()===nick.replace(/^@/,'').toLowerCase());if(!friend)return toast('Сначала добавьте пользователя в друзья');let role=p.roles.find(r=>r.name==='Участник')||p.roles[0],m=await api(`/projects/${p.id}/members`,{method:'POST',body:JSON.stringify({user_nickname:friend.user_nickname,role_ids:[role.id]})});let old=p.members.findIndex(x=>x.id===m.id);if(old>=0)p.members[old]=m;else p.members.push(m);render();toast('Участник подключён к проекту')}}catch(x){toast(x.message)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-team-action]');if(!b)return;try{if(b.dataset.teamAction==='channel'){activeChannel=b.dataset.id;chatMessages=[];await loadMessages(false);render()}if(b.dataset.teamAction==='newchannel'){let name=prompt('Название канала (без пробелов)');if(name){let c=await api(`/projects/${projectId}/channels`,{method:'POST',body:JSON.stringify({name})});project(projectId).channels.push(c);activeChannel=c.id;chatMessages=[];render()}}if(b.dataset.teamAction==='addcontact'){let email=prompt('Email пользователя'),tags=email?prompt('Теги/названия команд через запятую',''):null;if(email){let c=await api('/contacts',{method:'POST',body:JSON.stringify({email,tags:(tags||'').split(',').map(x=>x.trim()).filter(Boolean)})});S.contacts.push(c);render();toast('Контакт добавлен')}}if(b.dataset.teamAction==='editcontact'){let c=S.contacts.find(x=>x.id===b.dataset.id),tags=prompt('Теги/названия команд через запятую',(c.tags||[]).join(', '));if(tags!==null){let updated=await api(`/contacts/${c.id}`,{method:'PATCH',body:JSON.stringify({email:c.email,nickname:c.nickname||'',tags:tags.split(',').map(x=>x.trim()).filter(Boolean)})});Object.assign(c,updated);S.projects=await api('/projects');render();toast('Теги обновлены')}}if(b.dataset.teamAction==='teamlabel'){let p=project(projectId),label=prompt('Ярлык — название команды разработки',p.team_label||'');if(label!==null){let updated=await api(`/projects/${p.id}`,{method:'PATCH',body:JSON.stringify({name:p.name,description:p.description,color:p.color,team_label:label.trim()})});S.projects[S.projects.findIndex(x=>x.id===p.id)]=updated;render();toast('Ярлык сохранён, совпавшие контакты подключены')}}if(b.dataset.teamAction==='addmember'){let p=project(projectId),email=prompt('Email участника'),role=p.roles.find(r=>r.name==='Участник')||p.roles[0];if(email&&role){let m=await api(`/projects/${p.id}/members`,{method:'POST',body:JSON.stringify({email,role_ids:[role.id]})});p.members.push(m);render();toast('Участник подключён к проекту')}}if(b.dataset.teamAction==='newrole'){let p=project(projectId),name=prompt('Название роли');if(name){let r=await api(`/projects/${p.id}/roles`,{method:'POST',body:JSON.stringify({name,color:'#8b5cf6',permissions:['view','edit_tasks','send_messages']})});p.roles.push(r);render();toast('Роль создана')}}}catch(x){toast(x.message)}});
document.addEventListener('change',e=>{if(e.target.id==='team-project'){projectId=e.target.value;activeChannel=null;chatMessages=[];render()}});
document.addEventListener('submit',async e=>{if(e.target.id!=='chat-form')return;e.preventDefault();let content=e.target.content.value.trim(),attached_task_id=e.target.task.value||null;if(!content&&!attached_task_id)return;try{let m=await api(`/channels/${activeChannel}/messages`,{method:'POST',body:JSON.stringify({content,attached_task_id})});chatMessages.push(m);e.target.reset();render()}catch(x){toast(x.message)}},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='archive-settings')return;e.preventDefault();let data=Object.fromEntries(new FormData(e.target));try{S.user=await api('/auth/archive-settings',{method:'PATCH',body:JSON.stringify({policy:data.policy,days:+data.days})});render();toast('Настройки архива сохранены')}catch(x){toast(x.message)}},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='notification-settings')return;e.preventDefault();let rules={};e.target.querySelectorAll('[data-event]').forEach(row=>rules[row.dataset.event]={enabled:row.querySelector('[name="enabled"]').checked,channel:row.querySelector('[name="channel"]').value,priority:row.querySelector('[name="priority"]').value});try{S.user=await api('/auth/notification-settings',{method:'PATCH',body:JSON.stringify({rules})});render();toast('Настройки уведомлений сохранены')}catch(x){toast(x.message)}},true);
setInterval(()=>{if(page==='team'&&activeChannel)loadMessages(true)},5000);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-team-action="role"]');if(!b)return;e.stopPropagation();let p=project(projectId),m=p.members.find(x=>x.id===b.dataset.member),choice=prompt('Введите одну или несколько ролей через запятую:\n'+p.roles.map(r=>r.name).join('\n'),(m.roles||[{name:m.role}]).map(r=>r.name).join(', ')),names=(choice||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),roles=p.roles.filter(r=>names.includes(r.name.toLowerCase()));if(!roles.length||roles.length!==new Set(names).size)return toast('Одна из ролей не найдена');try{let updated=await api(`/members/${m.id}`,{method:'PATCH',body:JSON.stringify({email:m.email,role_ids:roles.map(r=>r.id)})});Object.assign(m,updated,{role_color:roles[0].color});render();toast('Роли назначены')}catch(x){toast(x.message)}},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='friend-search')return;e.preventDefault();let nick=new FormData(e.target).get('nickname').trim();try{friendResults=await api(`/users/search?q=${encodeURIComponent(nick)}`);render();if(!friendResults.length)toast('Пользователь не найден')}catch(x){toast(x.message)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-friend-add]');if(!b)return;e.preventDefault();try{let c=await api('/contacts',{method:'POST',body:JSON.stringify({user_nickname:b.dataset.friendAdd,tags:[]})});b.disabled=true;b.textContent='Запрос отправлен';toast(`Запрос для @${c.user_nickname} отправлен`)}catch(x){toast(x.message)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-friend-request]');if(!b)return;e.preventDefault();try{if(b.dataset.friendRequest==='accept'){let friend=await api(`/friend-requests/${b.dataset.id}/accept`,{method:'POST'});S.contacts.push(friend);toast(`@${friend.user_nickname} теперь в друзьях`)}else{await api(`/friend-requests/${b.dataset.id}/reject`,{method:'POST'});toast('Запрос отклонён')}S.friendRequests=S.friendRequests.filter(x=>x.id!==b.dataset.id);render()}catch(x){toast(x.message)}},true);

let uiResolve=null;function uiDialog(title,fields,submit='Сохранить'){let modal=$('#ui-modal'),form=$('#ui-form');$('#ui-title').textContent=title;$('#ui-fields').innerHTML=fields;$('#ui-submit').textContent=submit;modal.classList.remove('hidden');form.querySelector('input,select,textarea')?.focus();return new Promise(resolve=>uiResolve=resolve)}
function roleOptions(selected=[]){return S.friendRoles.map(r=>`<label class="check-label"><input type="checkbox" value="${r.id}" ${selected.includes(r.id)?'checked':''}> <span class="role-dot" style="background:${r.color}"></span>${esc(r.name)}</label>`).join('')||'<p class="meta">Сначала создайте роль.</p>'}
async function editRoleRule(kind,target,rules,permissions){if(!S.friendRoles.length)return toast('Сначала создайте роль в разделе «Друзья»');let pick=await uiDialog('Права роли',`<label>Роль<select name="role_id">${S.friendRoles.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label>`,'Далее');if(!pick)return;let current=(rules||[]).find(x=>x.role_id===pick.role_id)?.denied_permissions||[],checks=permissions.map(([v,n])=>`<label class="check-label"><input type="checkbox" value="${v}" ${current.includes(v)?'checked':''}> Запретить: ${n}</label>`).join(''),d=await uiDialog('Запреты для роли',`<fieldset><legend>${esc(S.friendRoles.find(r=>r.id===pick.role_id).name)}</legend>${checks}</fieldset>`);if(!d)return;let saved=await api(`/${kind}/${target}/role-rules`,{method:'PUT',body:JSON.stringify({role_id:pick.role_id,denied_permissions:d.checked})}),i=(rules||[]).findIndex(x=>x.role_id===pick.role_id);if(i<0)rules.push(saved);else rules[i]=saved;toast('Права роли сохранены')}
function closeUi(value=null){$('#ui-modal').classList.add('hidden');let done=uiResolve;uiResolve=null;if(done)done(value)}
$('#ui-form').addEventListener('submit',e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));data.checked=[...e.target.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value);closeUi(data)});$$('[data-ui-close]').forEach(x=>x.onclick=()=>closeUi());
function decorateUi(){let map={newproject:'newproject',editproject:'editproject',newcolumn:'newcolumn',newtemplate:'newtemplate'};Object.entries(map).forEach(([old,next])=>$$(`[data-action="${old}"]`).forEach(x=>{x.removeAttribute('data-action');x.dataset.uiAction=next}));['newchannel','addmember','newrole','teamlabel','editcontact','role'].forEach(old=>$$(`[data-team-action="${old}"]`).forEach(x=>{x.dataset.uiAction=old;x.removeAttribute('data-team-action')}))}
function positionCalendarEvents(){$$('.cal-event[data-id]').forEach(el=>{let task=S.tasks.find(t=>t.id===el.dataset.id),time=isoTime(task),minutes=+(time.split(':')[1]||0);el.style.top=`${3+Math.round(minutes/60*58)}px`})}
function decorateKanban(){if(page!=='projects')return;let p=project(projectId);if(!p)return;S.tasks.filter(t=>t.project_id===p.id&&t.column_id&&t.status!=='cancelled').forEach(t=>{let col=document.querySelector(`[data-column="${t.column_id}"]`),card=col?.querySelector(`[data-id="${t.id}"]`);if(!col)return;if(!card){let add=col.querySelector('[data-action="addcolumn"]');add?.insertAdjacentHTML('beforebegin',`<article class="kanban-card ${t.status==='completed'?'completed':''}" data-action="edit" data-id="${t.id}"><span class="priority ${t.priority}">${priorityLabel(t.priority)}</span><h4>${t.status==='completed'?'✓ ':''}${esc(t.title)}</h4><div class="meta"></div></article>`);card=col.querySelector(`[data-id="${t.id}"]`)}let actor=t.status==='in_progress'?t.started_by:t.status==='completed'?t.completed_by:null,meta=card?.querySelector('.meta');if(meta&&!meta.dataset.workflow){meta.dataset.workflow='1';meta.innerHTML=`${isoDate(t)?fmt(isoDate(t),{day:'numeric',month:'short'}):''}${t.assignee?` · Исполнитель: ${esc(t.assignee.name)}`:''}${actor?`<br>${t.status==='completed'?'Выполнил':'Взял в работу'}: ${esc(actor.name)}`:''}`}})}
function decorateNotifications(){updateProfileAvatar(S.user);let bell=$('#friends-alert'),count=S.notifications?.length||0;if(!bell)return;bell.classList.remove('hidden');bell.textContent=`🔔${count?` ${count}`:''}`;bell.title='Уведомления'}
new MutationObserver(()=>{decorateUi();positionCalendarEvents();decorateNotifications();decorateKanban()}).observe($('#content'),{childList:true,subtree:true});decorateUi();positionCalendarEvents();decorateNotifications();decorateKanban();
setInterval(updateCurrentTimeLines,30000);
document.addEventListener('click',async e=>{let b=e.target.closest('[data-ui-action]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();let action=b.dataset.uiAction,p=project(projectId);try{
if(action==='friendroles'){let d=await uiDialog('Новая роль друзей',`<label>Название<input name="name" required placeholder="Например, Подрядчик"></label><label>Цвет<input name="color" type="color" value="#5577e7"></label>`,'Создать');if(!d)return;let x=await api('/friend-roles',{method:'POST',body:JSON.stringify(d)});S.friendRoles.push(x);render();toast('Роль создана')}
if(action==='projectrules'){await editRoleRule('projects',p.id,p.role_rules,[['edit_tasks','изменение задач'],['manage_channels','изменение каналов'],['manage_members','добавление участников']]);render()}
if(action==='newproject'){let d=await uiDialog('Новый проект',`<label>Название<input name="name" required></label><label>Описание<textarea name="description" rows="3"></textarea></label><div class="form-grid"><label>Приоритет<select name="priority">${priorityOptions('P3')}</select></label><label>Цвет<input name="color" type="color" value="#5577e7"></label></div><label>Тег проекта<input name="team_label" placeholder="Например, работа"></label>`,'Создать');if(!d)return;let x=await api('/projects',{method:'POST',body:JSON.stringify(d)});S.projects.push(x);projectId=x.id;render()}
if(action==='editproject'){let d=await uiDialog('Редактировать проект',`<label>Название<input name="name" required value="${esc(p.name)}"></label><label>Описание<textarea name="description" rows="3">${esc(p.description||'')}</textarea></label><div class="form-grid"><label>Приоритет<select name="priority">${priorityOptions(p.priority)}</select></label><label>Цвет<input name="color" type="color" value="${esc(p.color)}"></label></div><label>Тег проекта<input name="team_label" value="${esc(p.team_label||'')}" placeholder="Например, работа"></label>`);if(!d)return;let x=await api(`/projects/${p.id}`,{method:'PATCH',body:JSON.stringify({...d,team_label:d.team_label.trim()})});S.projects[S.projects.findIndex(v=>v.id===p.id)]=x;render();toast('Проект обновлён')}
if(action==='newcolumn'){let d=await uiDialog('Новая колонка','<label>Название<input name="name" required></label>','Создать');if(!d)return;let x=await api(`/projects/${p.id}/columns`,{method:'POST',body:JSON.stringify({name:d.name})});p.columns.push(x);render()}
if(action==='newtemplate'){let d=await uiDialog('Новый шаблон',`<label>Название<input name="name" required></label><label>Описание<textarea name="description"></textarea></label><div class="form-grid"><label>Длительность, минут<input name="duration" type="number" value="60" min="0"></label><label>Приоритет<select name="priority">${priorityOptions('P3')}</select></label></div>`,'Создать');if(!d)return;d.duration=+d.duration;let x=await api('/templates',{method:'POST',body:JSON.stringify(d)});S.templates.push(x);render()}
if(action==='newchannel'){let friends=S.contacts.length?`<fieldset><legend>Сразу добавить друзей в проект</legend>${S.contacts.map(c=>`<label class="check-label"><input type="checkbox" value="${c.user_id}"> ${esc(c.nickname||c.name)} (@${esc(c.user_nickname)})</label>`).join('')}</fieldset>`:'<p class="meta">В списке друзей пока нет контактов.</p>',d=await uiDialog('Новый канал',`<label>Название без пробелов<input name="name" required pattern="[A-Za-zА-Яа-яЁё0-9_-]+"></label><label>Описание<input name="description"></label>${friends}`,'Создать');if(!d)return;let x=await api(`/projects/${p.id}/channels`,{method:'POST',body:JSON.stringify({name:d.name,description:d.description,contact_user_ids:d.checked})});S.projects=await api('/projects');projectId=p.id;activeChannel=x.id;chatMessages=[];render();toast(x.contacts_added?`Канал создан, добавлено друзей: ${x.contacts_added}`:'Канал создан')}
if(action==='channelmenu'){let c=p.channels.find(v=>v.id===b.dataset.id),choice=await uiDialog(`# ${esc(c.name)}`,`<label>Действие<select name="operation"><option value="permissions">Права ролей</option><option value="edit">Редактировать канал</option><option value="delete">Удалить канал</option></select></label>`,'Продолжить');if(!choice)return;if(choice.operation==='permissions'){await editRoleRule('channels',c.id,c.role_rules,[['view','чтение канала'],['send_messages','отправку сообщений'],['manage_members','добавление участников']]);render()}else if(choice.operation==='edit'){let d=await uiDialog('Редактировать канал',`<label>Название<input name="name" required pattern="[A-Za-zА-Яа-яЁё0-9_-]+" value="${esc(c.name)}"></label><label>Описание<input name="description" value="${esc(c.description||'')}"></label>`);if(!d)return;let x=await api(`/channels/${c.id}`,{method:'PATCH',body:JSON.stringify({name:d.name,description:d.description,contact_user_ids:[]})});Object.assign(c,x);render();toast('Канал обновлён')}else{let confirmDelete=await uiDialog(`Удалить #${esc(c.name)}?`,'<p>Все сообщения этого канала будут удалены без возможности восстановления.</p>','Удалить');if(!confirmDelete)return;await api(`/channels/${c.id}`,{method:'DELETE'});p.channels=p.channels.filter(v=>v.id!==c.id);if(activeChannel===c.id){activeChannel=p.channels[0]?.id||null;chatMessages=[]}render();toast('Канал удалён')}}
if(action==='teamlabel'){let d=await uiDialog('Ярлык команды',`<label>Название команды<input name="team_label" value="${esc(p.team_label||'')}"></label>`);if(!d)return;let x=await api(`/projects/${p.id}`,{method:'PATCH',body:JSON.stringify({name:p.name,description:p.description,color:p.color,priority:p.priority||'P3',team_label:d.team_label.trim()})});S.projects[S.projects.findIndex(v=>v.id===p.id)]=x;render()}
if(action==='newrole'){let perms=[['view','Просмотр'],['edit_tasks','Работа с задачами'],['send_messages','Сообщения'],['manage_channels','Каналы'],['manage_members','Участники']].map(([v,n])=>`<label class="check-label"><input type="checkbox" value="${v}" ${['view','edit_tasks','send_messages'].includes(v)?'checked':''}> ${n}</label>`).join('');let d=await uiDialog('Новая роль',`<label>Название<input name="name" required></label><label>Цвет<input name="color" type="color" value="#8b5cf6"></label><fieldset><legend>Разрешения</legend>${perms}</fieldset>`,'Создать');if(!d)return;let x=await api(`/projects/${p.id}/roles`,{method:'POST',body:JSON.stringify({name:d.name,color:d.color,permissions:d.checked})});p.roles.push(x);render()}
if(action==='addmember'){if(!S.contacts.length)return toast('Сначала добавьте пользователя в друзья');let available=S.contacts.filter(c=>!p.members.some(m=>m.user_id===c.user_id));if(!available.length)return toast('Все друзья уже добавлены в проект');let friends=available.map(c=>`<option value="${esc(c.user_nickname)}">${esc(c.name)} (@${esc(c.user_nickname)})</option>`).join(''),roles=p.roles.filter(r=>r.name!=='Владелец'&&r.name!=='Администратор'&&(r.permissions||[]).includes('view')).map(r=>`<label class="check-label"><input type="checkbox" value="${r.id}" ${r.name==='Участник'?'checked':''}> ${esc(r.name)}</label>`).join('');let d=await uiDialog('Добавить в проект',`<p class="meta">Участник увидит канбан проекта и доступные ему каналы.</p><label>Друг<select name="user_nickname">${friends}</select></label><fieldset><legend>Роли с доступом к проекту</legend>${roles}</fieldset>`,'Добавить');if(!d)return;if(!d.checked.length)return toast('Выберите хотя бы одну роль');let x=await api(`/projects/${p.id}/members`,{method:'POST',body:JSON.stringify({user_nickname:d.user_nickname,role_ids:d.checked})});let i=p.members.findIndex(v=>v.id===x.id);if(i<0)p.members.push(x);else p.members[i]=x;render();toast('Участник добавлен: канбан доступен')}
if(action==='role'){let m=p.members.find(x=>x.id===b.dataset.member),roles=p.roles.filter(r=>r.name!=='Владелец'&&r.name!=='Администратор'&&(r.permissions||[]).includes('view')).map(r=>`<label class="check-label"><input type="checkbox" value="${r.id}" ${(m.role_ids||[]).includes(r.id)?'checked':''}> ${esc(r.name)}</label>`).join(''),d=await uiDialog(`Роли: ${m.name}`,`<fieldset><legend>Роли с доступом к проекту и канбану</legend>${roles}</fieldset>`);if(!d)return;if(!d.checked.length)return toast('Выберите хотя бы одну роль');let x=await api(`/members/${m.id}`,{method:'PATCH',body:JSON.stringify({user_nickname:m.nickname,role_ids:d.checked})});Object.assign(m,x);render()}
if(action==='editcontact'){let c=S.contacts.find(x=>x.id===b.dataset.id),d=await uiDialog(`Друг @${c.user_nickname}`,`<label>Имя только для вас<input name="nickname" value="${esc(c.nickname||'')}"></label><label>Теги команд<input name="tags" value="${esc((c.tags||[]).join(', '))}"></label><fieldset><legend>Глобальные роли</legend>${roleOptions(c.role_ids||[])}</fieldset>`);if(!d)return;let x=await api(`/contacts/${c.id}`,{method:'PATCH',body:JSON.stringify({email:c.email,nickname:d.nickname,tags:d.tags.split(',').map(v=>v.trim()).filter(Boolean),role_ids:d.checked})});Object.assign(c,x);S.projects=await api('/projects');render()}
}catch(x){toast(x.message)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('#delete-task');if(!b)return;e.preventDefault();e.stopImmediatePropagation();let d=await uiDialog('Удалить задачу?','<p>Задача будет перемещена в архив и исчезнет из списков.</p>','Удалить');if(!d)return;let id=$('#task-form').elements.id.value;await api('/tasks/'+id,{method:'DELETE'});S.tasks=S.tasks.filter(x=>x.id!==id);closeModal();render();toast('Задача удалена')},true);
