"""friend roles and scoped access rules"""
from alembic import op
import sqlalchemy as sa
revision="0006";down_revision="0005";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("friend_roles",sa.Column("id",sa.String(36),primary_key=True),sa.Column("owner_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(80),nullable=False),sa.Column("color",sa.String(20),nullable=False),sa.UniqueConstraint("owner_user_id","name"));op.create_index("ix_friend_roles_owner_user_id","friend_roles",["owner_user_id"])
    op.create_table("contact_friend_roles",sa.Column("id",sa.String(36),primary_key=True),sa.Column("contact_id",sa.String(36),sa.ForeignKey("contacts.id",ondelete="CASCADE"),nullable=False),sa.Column("role_id",sa.String(36),sa.ForeignKey("friend_roles.id",ondelete="CASCADE"),nullable=False),sa.UniqueConstraint("contact_id","role_id"));op.create_index("ix_contact_friend_roles_contact_id","contact_friend_roles",["contact_id"]);op.create_index("ix_contact_friend_roles_role_id","contact_friend_roles",["role_id"])
    op.create_table("project_role_rules",sa.Column("id",sa.String(36),primary_key=True),sa.Column("project_id",sa.String(36),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("role_id",sa.String(36),sa.ForeignKey("friend_roles.id",ondelete="CASCADE"),nullable=False),sa.Column("denied_permissions",sa.JSON(),nullable=False),sa.UniqueConstraint("project_id","role_id"));op.create_index("ix_project_role_rules_project_id","project_role_rules",["project_id"]);op.create_index("ix_project_role_rules_role_id","project_role_rules",["role_id"])
    op.create_table("channel_role_rules",sa.Column("id",sa.String(36),primary_key=True),sa.Column("channel_id",sa.String(36),sa.ForeignKey("chat_channels.id",ondelete="CASCADE"),nullable=False),sa.Column("role_id",sa.String(36),sa.ForeignKey("friend_roles.id",ondelete="CASCADE"),nullable=False),sa.Column("denied_permissions",sa.JSON(),nullable=False),sa.UniqueConstraint("channel_id","role_id"));op.create_index("ix_channel_role_rules_channel_id","channel_role_rules",["channel_id"]);op.create_index("ix_channel_role_rules_role_id","channel_role_rules",["role_id"])
def downgrade():
    op.drop_table("channel_role_rules");op.drop_table("project_role_rules");op.drop_table("contact_friend_roles");op.drop_table("friend_roles")
