import {api} from './api.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={userId:null,status:null,conversations:[],active:null,messages:[],draft:'',search:'',day:'',busy:false,error:'',loading:false,requestKey:null};
const fields={title:'Название',description:'Описание',status:'Статус',priority:'Приоритет',start_at:'Начало',end_at:'Окончание',deadline_at:'Дедлайн',duration_minutes:'Минуты'};
const labels={planned:'Запланировано',idea:'Идея',in_progress:'В работе',completed:'Завершено',cancelled:'Отменено',pending:'Ожидает подтверждения',applied:'Применено',rejected:'Отклонено'};
const value=(key,v)=>v==null?'—':labels[v]||String(v);
const localDate=v=>v?String(v).slice(0,16):'';
function planHTML(p){const plan=p.plan||{},pending=p.status==='pending';return `<section class="ai-proposal ai-project-plan"><strong>План проекта · ${esc(labels[p.status]||p.status)}</strong>
  <form class="ai-plan-form" data-id="${p.id}"><label>Проект<input name="project_name" required maxlength="160" value="${esc(plan.project_name)}" ${pending?'':'disabled'}></label><label>Описание<textarea name="project_description" maxlength="4000" ${pending?'':'disabled'}>${esc(plan.project_description)}</textarea></label>
  <input type="hidden" name="goal_id" value="${esc(plan.goal_id||'')}"><input type="hidden" name="color" value="${esc(plan.color||'#5577e7')}"><input type="hidden" name="project_priority" value="${esc(plan.priority||'P3')}">
  ${(plan.stages||[]).map((stage,index)=>`<fieldset><legend>Этап ${index+1}</legend><label>Название<input name="stage_title" required maxlength="500" value="${esc(stage.title)}" ${pending?'':'disabled'}></label><label>Описание<textarea name="stage_description" maxlength="2000" ${pending?'':'disabled'}>${esc(stage.description||'')}</textarea></label><div class="ai-toolbar"><label>Приоритет<select name="stage_priority" ${pending?'':'disabled'}>${['P1','P2','P3','P4'].map(v=>`<option ${stage.priority===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Начало<input type="datetime-local" name="stage_start" value="${esc(localDate(stage.start_at))}" ${pending?'':'disabled'}></label><label>Дедлайн<input type="datetime-local" name="stage_deadline" value="${esc(localDate(stage.deadline_at))}" ${pending?'':'disabled'}></label><label>Минуты<input type="number" name="stage_duration" min="1" max="10080" value="${esc(stage.duration_minutes||60)}" ${pending?'':'disabled'}></label></div></fieldset>`).join('')}
  ${pending?`<button class="secondary" type="submit" ${state.busy?'disabled':''}>Сохранить правки</button> <button class="primary" type="button" data-ai-action="confirm" data-id="${p.id}" ${state.busy?'disabled':''}>Создать проект и этапы</button> <button class="secondary" type="button" data-ai-action="reject" data-id="${p.id}" ${state.busy?'disabled':''}>Отклонить</button>`:`${p.result?.project_name?`<p>Создан проект «${esc(p.result.project_name)}» и задач: ${esc((p.result.task_ids||[]).length)}</p>`:''}`}</form></section>`}
export function proposalHTML(p){if(p.kind==='project_plan')return planHTML(p);return `<section class="ai-proposal"><strong>${p.kind==='create_task'?'Создать личную задачу':'Изменить задачу'} · ${esc(labels[p.status]||p.status)}</strong><table><thead><tr><th>Поле</th><th>Было</th><th>Станет</th></tr></thead><tbody>${Object.entries(p.changes).map(([key,v])=>`<tr><td>${esc(fields[key]||key)}</td><td>${esc(value(key,p.before[key]))}</td><td>${esc(value(key,v))}</td></tr>`).join('')}</tbody></table>${p.status==='pending'?`<button class="primary" data-ai-action="confirm" data-id="${p.id}" ${state.busy?'disabled':''}>Подтвердить</button> <button class="secondary" data-ai-action="reject" data-id="${p.id}" ${state.busy?'disabled':''}>Отклонить</button>`:''}</section>`}
export function answerHTML(row){return `<article class="ai-turn"><p class="ai-user"><b>Вы</b><br>${esc(row.prompt)}</p><p class="ai-answer"><b>Помощник${state.status?.provider==='demo'?' · тестовый режим':''}</b><br>${esc(row.answer||(row.status==='running'?'Обрабатываю запрос…':'Ответ ещё не готов'))}</p>${(row.sources||[]).length?`<details><summary>Задачи, переданные в контекст (${row.sources.length})</summary>${row.sources.map(t=>`<button class="secondary" data-ai-action="task" data-id="${t.id}">${esc(t.title)}</button>`).join('')}</details>`:''}${(row.proposals||[]).map(proposalHTML).join('')}</article>`}
function content(){const s=state.status,enabled=s?.access&&s?.ready;return `<div class="page-head"><h1>AI-помощник</h1><button class="secondary" data-ai-action="reload">Обновить</button></div>
  ${state.error?`<p role="alert">${esc(state.error)}</p>`:''}
<p>${!s?'Загружаю состояние модуля…':!s.enabled?'AI-модуль выключен. Основной ежедневник работает независимо.':!s.access?'Доступ к AI не включён для вашего пользователя.':!s.ready?'Нужно настроить провайдера на сервере приложения.':s.provider==='demo'?'Тестовый режим без LLM: данные не отправляются во внешние сервисы. Команды: «Создай: название», «Заверши: точное название», «План проекта: название».':`Провайдер: ${esc(s.provider==='deepseek'?'DeepSeek':'OpenAI')} · ${esc(s.model||'')}. Запрос и выбранные данные ежедневника будут отправлены этому внешнему AI-сервису.`}</p>
  ${s?`<p class="meta">Запросы за день: ${s.used} / ${s.daily_limit}. Сброс в 00:00 UTC. Изменения — только после подтверждения каждого предложения.</p>`:''}
  <div class="ai-toolbar"><select id="ai-conversation" aria-label="Диалог" ${state.busy?'disabled':''}><option value="">Выберите диалог</option>${state.conversations.map(c=>`<option value="${c.id}" ${c.id===state.active?'selected':''}>${esc(c.title)}</option>`).join('')}</select><button class="secondary" data-ai-action="new" ${!enabled||state.busy?'disabled':''}>Новый диалог</button><button class="secondary" data-ai-action="delete" ${!state.active||state.busy?'disabled':''}>Удалить историю диалога</button></div>
  <div class="ai-history" aria-live="polite">${state.messages.map(answerHTML).join('')||'<p>Задайте вопрос о задачах, проектах или целях.</p>'}</div>
  <form id="ai-chat-form"><div class="ai-toolbar"><label>Поиск по задачам<input name="search" maxlength="100" value="${esc(state.search)}"></label><label>День календаря (необязательно)<input name="day" type="date" value="${esc(state.day)}"></label></div><p class="meta">До 50 доступных неархивных задач, 20 проектов и 10 личных целей. Внешние календари не включены. Помощник учитывает до шести предыдущих реплик этого диалога.</p><label>Запрос<textarea name="message" rows="3" required maxlength="2000" ${!enabled||state.busy?'disabled':''}>${esc(state.draft)}</textarea></label><button class="primary" ${!enabled||state.busy?'disabled':''}>${state.busy?'Обработка…':'Отправить'}</button>${state.busy?'<button type="button" class="secondary" data-ai-action="cancel">Отменить запрос</button>':''}</form>`}
function paint(){const node=document.querySelector('#ai-panel');if(node)node.innerHTML=content()}
async function reload(){[state.status,state.conversations]=await Promise.all([api('/ai/status'),api('/ai/conversations')]);if(state.active)state.messages=await api('/ai/conversations/'+state.active);paint()}
export function renderAI(user){if(state.userId!==user.id){state={...state,userId:user.id,status:null,active:null,messages:[],conversations:[],draft:'',busy:false,loading:false}}
  if(!state.status&&!state.loading){state.loading=true;queueMicrotask(async()=>{try{await reload()}catch(e){state.error=e.message}finally{state.loading=false;paint()}})}
  return '<section id="ai-panel">'+content()+'</section>';
}
document.addEventListener('input',e=>{if(!e.target.closest('#ai-chat-form'))return;if(e.target.name==='message')state.draft=e.target.value;else if(e.target.name==='search')state.search=e.target.value;else if(e.target.name==='day')state.day=e.target.value});
document.addEventListener('change',async e=>{if(e.target.id!=='ai-conversation')return;state.active=e.target.value||null;state.messages=[];try{await reload()}catch(error){state.error=error.message;paint()}});
document.addEventListener('submit',async e=>{if(e.target.id!=='ai-chat-form')return;e.preventDefault();if(state.busy)return;state.busy=true;state.error='';state.requestKey=crypto.randomUUID();paint();try{
  if(!state.active){const c=await api('/ai/conversations',{method:'POST'});state.active=c.id}
  const row=await api(`/ai/conversations/${state.active}/messages`,{method:'POST',body:JSON.stringify({request_key:state.requestKey,message:state.draft,search:state.search,day:state.day||null})});
  if(row.status==='completed')state.draft='';await reload();
}catch(error){state.error=error.message}finally{state.busy=false;state.requestKey=null;paint()}});
document.addEventListener('submit',async e=>{if(!e.target.matches('.ai-plan-form'))return;e.preventDefault();if(state.busy)return;state.busy=true;state.error='';const form=e.target,fd=new FormData(form),dates=v=>v?new Date(v).toISOString():null,titles=fd.getAll('stage_title'),descriptions=fd.getAll('stage_description'),priorities=fd.getAll('stage_priority'),starts=fd.getAll('stage_start'),deadlines=fd.getAll('stage_deadline'),durations=fd.getAll('stage_duration');try{
  const plan={project_name:fd.get('project_name'),project_description:fd.get('project_description'),color:fd.get('color'),priority:fd.get('project_priority'),goal_id:fd.get('goal_id')||null,stages:titles.map((title,i)=>({title,description:descriptions[i]||'',priority:priorities[i]||'P3',start_at:dates(starts[i]),end_at:null,deadline_at:dates(deadlines[i]),duration_minutes:Number(durations[i]||60)}))};
  await api(`/ai/proposals/${form.dataset.id}/project-plan`,{method:'PATCH',body:JSON.stringify({plan})});await reload();
}catch(error){state.error=error.message}finally{state.busy=false;paint()}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-ai-action]');if(!b)return;const action=b.dataset.aiAction;if(state.busy&&!['cancel','task'].includes(action))return;try{
  state.error='';
  if(action==='task'){document.dispatchEvent(new CustomEvent('ai-open-task',{detail:b.dataset.id}));return}
  if(action==='cancel'){
    if(!state.active)return;const rows=await api('/ai/conversations/'+state.active);const row=rows.find(r=>r.request_key===state.requestKey&&r.status==='running');
    if(row)await api(`/ai/requests/${row.id}/cancel`,{method:'POST'});
    state.error='Отмена запрошена. Внешний вызов может завершиться позже и учитываться в лимите.';await reload();return;
  }
  if(action==='new'){const c=await api('/ai/conversations',{method:'POST'});state.active=c.id;state.messages=[]}
  if(action==='delete'){if(!confirm('Удалить переписку и неприменённые предложения? Задачи сохранятся.'))return;await api('/ai/conversations/'+state.active,{method:'DELETE'});state.active=null;state.messages=[]}
  if(['confirm','reject'].includes(action)){state.busy=true;paint();await api(`/ai/proposals/${b.dataset.id}/decision`,{method:'POST',body:JSON.stringify({decision:action})});document.dispatchEvent(new Event('ai-tasks-changed'))}
  await reload();
}catch(error){state.error=error.message}finally{if(!['cancel','task'].includes(action))state.busy=false;paint()}});
