const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,c)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:c}).format(+v);
export function renderFinance(s){
 const accounts=s.financeAccounts||[],txs=s.financeTransactions||[],analytics=s.financeAnalytics||{totals:[],planned:[],by_category:[],timeline:[]},planned=s.financePlanned||[];
 const accountName=id=>accounts.find(a=>a.id===id)?.name||'Счёт';
 return `<div class="page-head"><div><span class="eyebrow">ЛИЧНЫЕ ДАННЫЕ</span><h1>Финансы</h1><p>Факт, планы и цели — отдельно по каждой валюте.</p></div><div><button class="secondary" data-finance="account">＋ Счёт</button> <button class="primary" data-finance="transaction">＋ Операция</button></div></div>
 <div class="finance-tabs"><button data-finance-tab="overview">Обзор</button><button data-finance-tab="accounts">Счета</button><button data-finance-tab="transactions">Операции</button><button data-finance-tab="analytics">Аналитика / отчёты</button></div>
 <div class="stats">${accounts.length?[...new Set(accounts.map(a=>a.currency))].map(c=>`<div class="stat"><strong>${fmt(accounts.filter(a=>a.currency===c).reduce((n,a)=>n+(+a.balance),0),c)}</strong><small>доступно сейчас</small></div>`).join(''):'<div class="stat"><strong>0</strong><small>создайте первый счёт</small></div>'}${analytics.totals.map(t=>`<div class="stat"><strong class="positive">+${fmt(t.income,t.currency)}</strong><small>доходы периода</small></div><div class="stat"><strong class="negative">−${fmt(t.expense,t.currency)}</strong><small>расходы периода</small></div>`).join('')}</div>
 <div class="finance-grid"><section class="card"><div class="card-title">Счета</div>${accounts.map(a=>`<div class="finance-row"><span>${esc(a.name)}<small>${esc(a.type)}</small></span><b>${fmt(a.balance,a.currency)}</b></div>`).join('')||'<p class="empty">Счетов пока нет</p>'}</section>
 <section class="card"><div class="card-title">Ближайшие платежи</div>${planned.filter(p=>!p.transaction_id).slice(0,8).map(p=>`<div class="finance-row"><span>${esc(s.tasks.find(t=>t.id===p.task_id)?.title||'Финансовая задача')}<small>${p.planned_at?.slice(0,10)||'без даты'} · запланировано</small></span><b class="${p.type==='expense'?'negative':'positive'}">${p.type==='expense'?'−':'+'}${fmt(p.amount,p.currency)}</b><button class="secondary" data-finance-execute="${p.task_id}">Провести</button></div>`).join('')||'<p class="empty">Нет запланированных платежей</p>'}</section></div>
 <section class="card"><div class="card-title"><span>Последние операции</span><a class="secondary" href="/api/v1/finance/report?format=csv">CSV</a></div>${txs.slice(0,15).map(t=>`<div class="finance-row"><span>${esc(t.description||({income:'Доход',expense:'Расход',transfer:'Перевод'}[t.type]))}<small>${t.transaction_at.slice(0,10)} · ${esc(accountName(t.account_id))}</small></span><b class="${t.type==='expense'?'negative':t.type==='income'?'positive':''}">${t.type==='expense'?'−':t.type==='income'?'+':'↔ '}${fmt(t.amount,t.currency)}</b></div>`).join('')||'<p class="empty">Операций пока нет</p>'}</section>
 <section class="card"><div class="card-title">План / факт</div>${analytics.totals.concat(analytics.planned).length?`<div class="chart-bars">${analytics.totals.map(t=>`<div><span>Факт ${t.currency}</span><i style="--bar:${Math.min(100,+t.expense/Math.max(1,+t.income,+t.expense)*100)}%"></i><b>${fmt(t.expense,t.currency)}</b></div>`).join('')}${analytics.planned.map(t=>`<div><span>План ${t.currency}</span><i class="planned" style="--bar:${Math.min(100,+t.expense/Math.max(1,+t.income,+t.expense)*100)}%"></i><b>${fmt(t.expense,t.currency)}</b></div>`).join('')}</div>`:'<p class="empty">График появится из реальных операций и задач</p>'}</section>`;
}

export function bindFinance(ctx){
 document.addEventListener('click',async e=>{let b=e.target.closest('[data-finance],[data-finance-execute]');if(!b)return;try{
  if(b.dataset.financeExecute){await ctx.api(`/finance/tasks/${b.dataset.financeExecute}/execute`,{method:'POST'});await ctx.reload();ctx.toast('Задача выполнена, операция проведена');return}
  if(b.dataset.finance==='account'){let d=await ctx.dialog('Новый счёт','<label>Название<input name="name" required></label><label>Тип<select name="type"><option value="bank_card">Банковская карта</option><option value="bank_account">Банковский счёт</option><option value="cash">Наличные</option><option value="savings">Накопительный счёт</option><option value="other">Другое</option></select></label><div class="form-grid"><label>Валюта<input name="currency" value="RUB" pattern="[A-Z]{3}"></label><label>Начальный баланс<input name="opening_balance" type="number" step="0.01" value="0"></label></div>','Создать');if(!d)return;await ctx.api('/finance/accounts',{method:'POST',body:JSON.stringify({...d,is_archived:false})})}
  if(b.dataset.finance==='transaction'){let accounts=ctx.state.financeAccounts;if(!accounts.length)throw new Error('Сначала создайте счёт');let cats=ctx.state.financeCategories,d=await ctx.dialog('Новая операция',`<label>Тип<select name="type"><option value="expense">Расход</option><option value="income">Доход</option><option value="transfer">Перевод</option></select></label><div class="form-grid"><label>Сумма<input name="amount" type="number" step="0.01" min="0.01" required></label><label>Счёт<select name="account_id">${accounts.map(a=>`<option value="${a.id}">${esc(a.name)} · ${a.currency}</option>`).join('')}</select></label></div><label>Счёт назначения (для перевода)<select name="destination_account_id"><option value="">—</option>${accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>Категория<select name="category_id"><option value="">Без категории</option>${cats.map(c=>`<option value="${c.id}">${esc(c.name)} · ${c.type}</option>`).join('')}</select></label><label>Описание<input name="description"></label>`,'Добавить');if(!d)return;let a=accounts.find(a=>a.id===d.account_id);await ctx.api('/finance/transactions',{method:'POST',body:JSON.stringify({...d,destination_account_id:d.destination_account_id||null,category_id:d.category_id||null,currency:a.currency,transaction_at:new Date().toISOString(),task_id:null,project_id:null,goal_id:null,goal_contribution:false})})}
  await ctx.reload();ctx.toast('Финансы обновлены')
 }catch(x){ctx.toast(x.message)}},true)
}
